### ISSUE TITLE
Filip.R - The `totalWeight` calculation logic is different in the two functions.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#100]
Filip.R

High

# The `totalWeight` calculation logic is different in the two functions.

## Summary
The `totalWeight` calculation logic is different in the two functions - `poke` and `_reset`.

## Vulnerability Detail

In the `poke` function, _weight is always calculated under the condition that `votes[_tokenId][_pool] > 0`.
However, additional logic was created in the `_reset` function when `votes[_tokenId][_pool] < 0`, which results in different calculation results.

    function _reset(uint _tokenId) internal {
        address[] storage _poolVote = poolVote[_tokenId];
        uint _poolVoteCnt = _poolVote.length;
        uint256 _totalWeight = 0;

        for (uint i = 0; i < _poolVoteCnt; i ++) {
            address _pool = _poolVote[i];
            uint256 _votes = votes[_tokenId][_pool];

            if (_votes != 0) {
                _updateFor(gauges[_pool]);
                weights[_pool] -= _votes;
                votes[_tokenId][_pool] -= _votes;
       @>>>         if (_votes > 0) {
                    IBribe(external_bribes[gauges[_pool]])._withdraw(uint256(_votes), _tokenId);
       @>>>            _totalWeight += _votes;
                } else {
       @>>>             _totalWeight -= _votes;
                }
                emit Abstained(_tokenId, _votes);
            }
        }
        totalWeight -= uint256(_totalWeight);
        usedWeights[_tokenId] = 0;
        delete poolVote[_tokenId];
    }

and

    function poke(uint _tokenId) external onlyNewEpoch(_tokenId) {
        require(IVotingEscrow(_ve).isApprovedOrOwner(msg.sender, _tokenId) || msg.sender == governor);
        lastVoted[_tokenId] = block.timestamp;

        address[] memory _poolVote = poolVote[_tokenId];
        uint _poolCnt = _poolVote.length;
        uint256[] memory _weights = new uint256[](_poolCnt);

        for (uint i = 0; i < _poolCnt; i ++) {
     @>>>       _weights[i] = votes[_tokenId][_poolVote[i]];
        }

        _vote(_tokenId, _poolVote, _weights);
    }

## Impact
Different calculation logic results in token loss and uncertainty.

## Code Snippet

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Voter.sol#L224

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Voter.sol#L243

## Tool used

Manual Review

## Recommendation

If the `votes[_tokenId][_pool] < 0` logic of the `_reset` function is correct, the same calculation logic must be added to the `poke` function.

**Comment by nevillehuang** [comment]
Invalid, per issue #361, the else block will never be reached given `votes` is declared as a uint256 and so will not be less than zero
