### ISSUE TITLE
1337web3 - Non Compliance With ERC165

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#112]
1337web3

Medium

# Non Compliance With ERC165

## Summary
The `VotingEscrow` contract does not fully comply with the ERC165 specification, which is necessary by design.

## Vulnerability Detail
The ERC165 standard defines a method to publish and detect the interfaces that a given contract implements. Although `VotingEscrow` contains the required functions, the issue arises because `VotingEscrow::supportsInterface` will return `false` for the `IVotes` interface, even though `VotingEscrow` actually implements it. This discrepancy can lead to issues when interacting with the `VotingEscrow` contract.
More information about ERC165 can be found here: https://eips.ethereum.org/EIPS/eip-165

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/VotingEscrow.sol#L112-L114

## Impact
The incorrect implementation of `supportsInterface` can cause compatibility issues with other contracts or tools that rely on ERC165 to detect supported interfaces. This might result in failed interactions or reduced functionality when these contracts or tools attempt to work with `VotingEscrow`.

## Code Snippet
```solidity
contract VotingEscrow is IERC721, IERC721Metadata, IVotes {
	...
	
	constructor(address base_token_addr,address lp_token_addr, address art_proxy, address _owner) {
        baseToken = base_token_addr;
        lpToken = lp_token_addr;
        voter = msg.sender;
        team = msg.sender;
        artProxy = art_proxy;
        owner = _owner;

        point_history[0].blk = block.number;
        point_history[0].ts = block.timestamp;

        supportedInterfaces[ERC165_INTERFACE_ID] = true;
        supportedInterfaces[ERC721_INTERFACE_ID] = true;
        supportedInterfaces[ERC721_METADATA_INTERFACE_ID] = true;

        // mint-ish
        emit Transfer(address(0), address(this), tokenId);
        // burn-ish
        emit Transfer(address(this), address(0), tokenId);
    }
    
	...
}
```

## Tool used
Manual Review

## Recommendation
Ensure that `VotingEscrow::supportsInterface` correctly returns `true` for the `IVotes` interface to comply with the ERC165 specification.

**Comment by nevillehuang** [comment]
Invalid, there are not ERC compliancy required in the protocol. Additionally this will not impact code logic of velocimeter

> > Q: Is the codebase expected to comply with any EIPs? Can there be/are there any deviations from the specification?
> No

**Comment by zyppyvids** [comment]
In the documentation, it is said that there are no EIPs that the codebase should be compliant with. However, in the code you can see that it is returning true for the ERC165 interface leading me to believe that this is a real problem.
