### ISSUE TITLE
1337web3 - Front Running Permit Causing DoS

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#114]
1337web3

Medium

# Front Running Permit Causing DoS

## Summary
The Pair contract's `permit` function is vulnerable to front-running attacks. This could potentially lead to denial-of-service (DoS) scenarios for users attempting to call the `permit` function.

## Vulnerability Detail
The `permit` function, as defined by EIP-2612 for ERC20 tokens, allows users to sign an approval off-chain and send it to a trusted service. The service can then use the funds as if the user called `approve()`. The function operates by validating a cryptographic signature of the following fields:
- `owner` (user)
- `spender` (trusted address)
- `value` (amount)
- `nonce` (an int that increases after every permit execution)
- `deadline`

When `permit()` executes, it checks:
1. The signature's validity (by comparing it to a signature constructed using parameters and the user's nonce).
2. The deadline has not passed.

By design, the token ignores the `msg.sender` of the `permit()` call. This, combined with the fact that transactions (TXs) can be observed in the mempool (by anyone or at least by the sequencer in some L2s), means that a `permit()` call can be easily front-run by simply duplicating the transaction arguments.
More information about the issue can be found here: https://www.trust-security.xyz/post/permission-denied 

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Pair.sol#L434-L457

## Impact
Any function call that unconditionally performs `permit()` can be forced to revert via front-running. If there is a fallback code path using direct user approval, the denial-of-service (DoS) is short-term, as the user or dApp could eventually switch to using an alternative. Otherwise, the DoS is long-term. While there are bypasses through flashbots in some chains, resorting to them is far from ideal. Consequently, a malicious actor can front-run a `permit()` call, causing the described griefing effect.

## Code Snippet
```solidity
function permit(address owner, address spender, uint value, uint deadline, uint8 v, bytes32 r, bytes32 s) external {
	require(deadline >= block.timestamp, 'Pair: EXPIRED');
	DOMAIN_SEPARATOR = keccak256(
		abi.encode(
			keccak256('EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)'),
			keccak256(bytes(name)),
			keccak256(bytes('1')),
			block.chainid,
			address(this)
		)
	);
	bytes32 digest = keccak256(
		abi.encodePacked(
			'\x19\x01',
			DOMAIN_SEPARATOR,
			keccak256(abi.encode(PERMIT_TYPEHASH, owner, spender, value, nonces[owner]++, deadline))
		)
	);
	address recoveredAddress = ecrecover(digest, v, r, s);
	require(recoveredAddress != address(0) && recoveredAddress == owner, 'Pair: INVALID_SIGNATURE');
	allowance[owner][spender] = value;

	emit Approval(owner, spender, value);
}
```

## Tool used
Manual Review

## Recommendation
Implement measures to mitigate front-running attacks on the `permit` function. There is a mitigation listed in this article: https://www.trust-security.xyz/post/permission-denied

**Comment by nevillehuang** [comment]
Invalid, the nonce increment for each permit transaction will make this attack not possible

**Comment by zyppyvids** [comment]
In the article provided by Trust you can clearly see that the nonce increment does not fix this issue.
