### ISSUE TITLE
1337web3 - Wrong TransferFrom Allowance Implementation

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#115]
1337web3

Medium

# Wrong TransferFrom Allowance Implementation

## Summary
An issue was identified in the `Flow` contract's `transferFrom` function, which incorrectly handles allowances when the caller and the `_from` address are the same. This can lead to unintended transaction reverts. 
The `Pair` contract has a correct implementation of the `transferFrom` function.

## Vulnerability Detail
In the `Flow` contract, the `transferFrom` function decreases the caller's allowance even if the caller is the same as the `_from` address. This is not the intended behavior, as it can cause the transaction to revert if the caller has not set their own allowance to the required value. 
The `Pair` contract properly implements a check to avoid reducing the allowance in such cases.

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Flow.sol#L72-L78

## Impact
Due to the lack of a check for whether the caller is the same as the `_from` address, users of the `Flow` contract may experience unintended transaction reverts. This can hinder the usability of the contract, as users must set their own allowance to transfer their own tokens.

## Code Snippet
**Flow.sol:**
```solidity
function transferFrom(address _from, address _to, uint _value) external returns (bool) {
    uint allowed_from = allowance[_from][msg.sender];
    if (allowed_from != type(uint).max) {
        allowance[_from][msg.sender] -= _value;
    }
    return _transfer(_from, _to, _value);
}
```

**Pair.sol:**
```solidity
function transferFrom(address src, address dst, uint amount) external returns (bool) {
    address spender = msg.sender;
    uint spenderAllowance = allowance[src][spender];

    if (spender != src && spenderAllowance != type(uint).max) {
        uint newAllowance = spenderAllowance - amount;
        allowance[src][spender] = newAllowance;

        emit Approval(src, spender, newAllowance);
    }

    _transferTokens(src, dst, amount);
    return true;
}
```

## Tool used
Manual Review

## Recommendation
Update the `Flow` contract's `transferFrom` function to include a check for whether the caller is the same as the `_from` address. The allowance should only be decreased if the caller is different from the `_from` address, similar to the implementation in the `Pair` contract.

**Comment by nevillehuang** [comment]
Invalid, explicit check is not required, given the owner can simply give themself the required allowance
