### ISSUE TITLE
uint6 - Lack of Zero Address Check

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#12]
uint6

Medium

# Lack of Zero Address Check

## Summary
The `totalSupply` of  token minted to zero address would increase by the minted amount.
## Vulnerability Detail

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Flow.sol#L80

The ```_mint```   function increases `totalSupply` regardless of the recipient, there's no check that prevent minting tokens to the zero address ```(0x0000000000000000000000000000000000000000```  which leads to a situation where `totalSupply` may increase even if tokens are minted to zero address  without the tokens being accessible to anyone.

Consider a scenario where minter could call `mint` function withe zero address the `totalSupply` may increases by `1000000000000000` while the  `balanceOf[_to] += _value;` may increases to 1000000000000000. and the  token will be locked forever.
     
```solidity
mint(address(0), 1000000000000000);
```

## Impact
Loss of user funds as the `totalSupply` will include the  minted tokens of the zero address, leading to an inflated total supply.
## Code Snippet

Mint function 

```solidity
    function _mint(address _to, uint _amount) internal returns (bool) {
        totalSupply += _amount;
        unchecked {
            balanceOf[_to] += _amount;
        }
        emit Transfer(address(0x0), _to, _amount);
        return true;
    }
 ```
## Tool used

Manual Review

## Recommendation
 implement a zero address  check, to ensure that the `totalSupply`  reflects the circulating supply.
 
 1. https://solodit.xyz/issues/h-05-making-_totalsupply-and-_totalshares-imbalance-significantly-by-providing-fake-income-leads-to-stealing-fund-code4rena-lybra-finance-lybra-finance-git
2. https://solodit.xyz/issues/h-01-wrong-fee-calculation-after-totalsupply-was-0-code4rena-kuiper-kuiper-contest-git

**Comment by nevillehuang** [comment]
Invalid, based on [sherlock rules](https://github.com/sherlock-protocol/sherlock-v2-docs/tree/29a019b8690eb01df3587868c4d7eac1e3459bda/audits/judging/judging#vii-list-of-issue-categories-that-are-not-considered-valid)

> 3. Zero address checks: Check to make sure input values are not zero addresses.
