### ISSUE TITLE
ravikiran.web3 - Owner is not initialized in GaugePlugin contract

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#16]
ravikiran.web3

Medium

# Owner is not initialized in GaugePlugin contract

## Summary
`_owner` variable in `Ownable` contract is initialized in either the constructor or through `transferOwnership()` function. The `GaugePlugin` contract does not pass the address in the constructor of `Ownable` or call `transferOwnership()` in the contructor.
Hence, the owner is not set.

## Vulnerability Detail
The state level variable is not initialized and hence owner for `GaugePlugin` contract is not set. As such, when the owner wants to set a new governor address, the functionality to set will not be available as the `_owner`  was left uninitialized.

## Impact
`setGovernor` function will not work, when the owner wants to set a new governor address.
## Code Snippet

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/GaugePlugin.sol#L8-L16

The `setGovernor` function will not work as the ownership was not initialized.

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/GaugePlugin.sol#L28-L31

## Tool used

Manual Review

## Recommendation

```solidity
 constructor(address flow, address weth, address _governor, address initialOwner)  Ownable(initialOwner)  {
        governor = _governor;
        isWhitelistedForGaugeCreation[flow] = true;
        isWhitelistedForGaugeCreation[weth] = true;
    }
```

**Comment by nevillehuang** [comment]
Invalid, the version of OpenZeppelin that the protocol uses automatically transfers ownership to deployer of contract as seen [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/d00acef4059807535af0bd0dd0ddf619747a044b/contracts/access/Ownable.sol#L28-L30)
