### ISSUE TITLE
Naresh - Unsafe casting in `RewardsDistributorV2` leads to underflow

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#166]
Naresh

Medium

# Unsafe casting in `RewardsDistributorV2` leads to underflow

## Summary
The `RewardsDistributorV2` contract has a vulnerability where casting a negative number to `uint` results in an underflow to a large number instead of reverting.

## Vulnerability Detail
Solidity does not revert when casting a negative number to `uint`. Instead, it underflows to a large number. In the `RewardsDistributorV2` contract, the balance of a token at specific time is calculated as follows:
```solidity
   function ve_for_at(uint _tokenId, uint _timestamp) external view returns (uint) {
          address ve = voting_escrow;
          uint max_user_epoch = IVotingEscrow(ve).user_point_epoch(_tokenId);
          uint epoch = _find_timestamp_user_epoch(ve, _tokenId, _timestamp, max_user_epoch);
          IVotingEscrow.Point memory pt = IVotingEscrow(ve).user_point_history(_tokenId, epoch);
@>        return Math.max(uint(int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts))))), 0);
   }
```
This supposes to return zero when the calculated balance is a negative number. However, it underflows to a large number.

## Impact
This would lead to incorrect reward distribution if third-party protocols depend on this function, or when further updates make use of this codebase.

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L139

https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L158

https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L208

https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L265

## Tool used
Manual Review

## Recommendation
Recommend following other parts of the codebase and returning zero for a negative number:
```solidity
int256 result = int256(pt.bias - pt.slope * int128(int256(_timestamp - pt.ts)));
if (result < 0) return 0;
return uint256(result);
```
Additionally, this fix should be applied to other parts of the `RewardsDistributorV2` contract where similar calculations are made, specifically at:
-  [RewardsDistributorV2.sol#L158](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L158)
- [RewardsDistributorV2.sol#L208](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L208)
- [RewardsDistributorV2.sol#L265](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L265)

**Comment by nevillehuang** [comment]
See comment [here](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/649#issuecomment-2283085297)
