### ISSUE TITLE
hl_ - Unsafe casting in `RewardsDistributorV2` leads to underflow of function `ve_for_at`

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#169]
hl_

Medium

# Unsafe casting in `RewardsDistributorV2` leads to underflow of function `ve_for_at`

## Summary
Unsafe casting in `RewardsDistributorV2` leads to underflow of function `ve_for_at`

## Vulnerability Detail
When casting a negative number to uint, Solidity does not revert. Instead, it underflows to a large number. In the `RewardDistributorV2` contract, the balance of a token at specific time is calculated as follows:

```javascript
 IVotingEscrow.Point memory pt = IVotingEscrow(ve).user_point_history(_tokenId, epoch);
        return Math.max(uint(int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts))))), 0);
    }
```
It is intended to return a zero value when the calculated balance is a negative number. However, it instead underflows to a large number. 

## Impact
This would lead to incorrect rewards distribution if third-party protocols depend on this function, or if further updates are made. 

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L134-L140

## Tool used
Manual Review

## Recommendation
Recommend to return zero for a negative number, for example: 

```javascript
int256 result = int256(pt.bias - pt.slope * int128(int256(_timestamp - pt.ts)));
if (result < 0) return 0;
return uint256(result);
```

**Comment by nevillehuang** [comment]
See comment [here](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/649#issuecomment-2283085297)
