### ISSUE TITLE
KungFuPanda - Pair.sol: Skimming may revert in pairs with at least one reverts-on-0-value-transfer token.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#17]
KungFuPanda

Medium

# Pair.sol: Skimming may revert in pairs with at least one reverts-on-0-value-transfer token.

## Summary
`Pair::skim()` may revert if the "excess" amount of one of the pair's tokens is `0`, if that token (`token0` or `token1`) is a **reverts-on-0-value-transfer** token.

## Vulnerability Detail
Consider a scenario in which the user accidentally transfers `10 scaled units` of `token0` to the `PairA` pair contract.

The `PairA` contract is a two-sided pair, in which the `token0` is a normal token (doesn't necessarily have to revert on 0 value transfers), and `token1` is a token that is a **reverts-on-0-value-transfers** token.

When the user attempts to call `skim(address to)` to get his `10 scaled units` of the `token0` back, if the current balance of `token1` is `0`, the whole `skim` call will revert.

## Impact
I believe it's **medium** severity, because it will cause persistent `skim` ***DoS*** and inability to skim the excess tokens from the `Pair`, until the user transfers some `token1` to the `PairA` contract in order to prevent the revert from happenning during the `_safeTransfer(_token1, to, IERC20(_token1).balanceOf(address(this)) - (reserve1));` operation.

## Code Snippet
```solidity
      // force balances to match reserves
      function skim(address to) external lock {
          (address _token0, address _token1) = (token0, token1);
@@        _safeTransfer(_token0, to, IERC20(_token0).balanceOf(address(this)) - (reserve0));
@@        _safeTransfer(_token1, to, IERC20(_token1).balanceOf(address(this)) - (reserve1));
      }
```

## Tool used
Manual human review.

## Recommendation
Consider adding some conditional operator checks to prevent the DoS:
```diff
      // force balances to match reserves
      function skim(address to) external lock {
          (address _token0, address _token1) = (token0, token1);
+         uint256 balance0 = IERC20(_token0).balanceOf(address(this));
+         uint256 balance1 = IERC20(_token1).balanceOf(address(this));

-         _safeTransfer(_token1, to, IERC20(_token0).balanceOf(address(this)) - (reserve1));
+         if ((balance0 - reserve0) > 0) _safeTransfer(_token0, to, balance0 - reserve0);
-         _safeTransfer(_token1, to, IERC20(_token1).balanceOf(address(this)) - (reserve1));
+         if ((balance1 - reserve1) > 0) _safeTransfer(_token1, to, balance1 - reserve0);
      }
```

## References
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Pair.sol#L338C1-L343C6

**Comment by nevillehuang** [comment]
Invalid, this type of weird tokens are not explictly mentioned to be supported as well, so likely invalid based on sherlock [rules](https://github.com/sherlock-protocol/sherlock-v2-docs/tree/29a019b8690eb01df3587868c4d7eac1e3459bda/audits/judging/judging#vii-list-of-issue-categories-that-are-not-considered-valid). 

> 23. Non-Standard tokens: Issues related to tokens with non-standard behaviors, such as weird-tokens are not considered valid by default unless these tokens are explicitly mentioned in the README.
