### ISSUE TITLE
blockchain555 - Gauge rewards may be transferred incorrectly after setting `_rewardsAddress` in the `OptionTokenV4` contract.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#177]
blockchain555

High

# Gauge rewards may be transferred incorrectly after setting `_rewardsAddress` in the `OptionTokenV4` contract.

## Summary
When setting `rewardsAddress` in the `OptionTokenV4` contract, rewards may be transferred incorrectly because the rewards accumulated in the contract are not distributed.
## Vulnerability Detail
The `OptionTokenV4.sol#setRewardsAddress()` function is a function that sets rewardsAddress.
```solidity
    function setRewardsAddress(address _rewardsAddress) external onlyAdmin {
        rewardsAddress = _rewardsAddress;
        emit SetRewardsAddress(_rewardsAddress);
    }
```
As you can see, in this function, `rewardsAddress` is set without transferring the rewards accumulated in the contract first.
The function that transfers compensation to the gauge is as follows.
```solidity
    function _transferRewardToGauge() internal {
        uint256 paymentTokenCollectedAmount = IERC20(paymentToken).balanceOf(address(this));

        if(rewardsAddress != address(0)) {
743:        _safeTransfer(paymentToken,rewardsAddress,paymentTokenCollectedAmount);
        } else {
            uint256 leftRewards = IGaugeV4(gauge).left(paymentToken);

            if(paymentTokenCollectedAmount > leftRewards) { // we are sending rewards only if we have more then the current rewards in the gauge
                _safeApprove(paymentToken, gauge, paymentTokenCollectedAmount);
                IGaugeV4(gauge).notifyRewardAmount(paymentToken, paymentTokenCollectedAmount);
            }
        }
    }
```
As you can see, when rewardsAddress is set, the entire reward accumulated in the contract is not transferred to the gauge, but to rewardsAddress.
However, since the reward is transferred to the gauge only when the conditions are met, the reward accumulated in the contract may have to be transferred to the gauge.
As a result, Gauge rewards may be transferred incorrectly.
## Impact
Gauge rewards may be transferred incorrectly after setting `_rewardsAddress` in the `OptionTokenV4` contract.
## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L453-L456
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L739-L752
## Tool used

Manual Review

## Recommendation
It is recommended to modify the `setRewardsAddress()` function as follows:
```solidity
    function setRewardsAddress(address _rewardsAddress) external onlyAdmin {
+++     _transferRewardToGauge();
        rewardsAddress = _rewardsAddress;
        emit SetRewardsAddress(_rewardsAddress);
    }
```

**Comment by nevillehuang** [comment]
Invalid, this does not seem like an issue, given it is at the discretion of the admin to decide on reward address. Additionally, all payment tokens would have been transferred to original reward address at time of option exercise
