### ISSUE TITLE
tvdung94 - Users will get much less discount than expected when exercising for liquid flow

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#187]
tvdung94

High

# Users will get much less discount than expected when exercising for liquid flow

## Summary
As stated by the sponsor, when exercising option flow for liquid flow, users will get 20% discount price (users will pay 80%).

> When you choose exercise to liquid FLOW (to sell it immediately on the market) you are paying like 80% of the value to exercise it.
> 
> So its a 20% discount vs 100% discount.

The problem is that for current implementation, users will have to pay 99% instead of 80% of the total value. 

## Vulnerability Detail
Discount payment is calculated as follow, proportional to `discount`:

```solidity
function getDiscountedPrice(uint256 _amount) public view returns (uint256) {
        return (getTimeWeightedAveragePrice(_amount) * discount) / 100;
    }
```

Since `discount`  is set to 99%, users will have to pay 99% (while intended payment amount is 80%)

```solidity
uint256 public discount = 99;
```

## Impact
Users have to pay much more than intended - loss of funds for users.
## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L323-L325
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L149
## Tool used

Manual Review

## Recommendation
Consider setting `discount` to 80% (users pay 80%)

**Comment by nevillehuang** [comment]
Invalid, doesn't seem to be an issue [here](https://discord.com/channels/812037309376495636/1257350045976760404/1263855039294734406). Additionally, discounts are determined by the admin and can always be adjusted as seen [here](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L460-L464)
