### ISSUE TITLE
tvdung94 - Weekly emission reward's amount will be less than expected in some certain cases

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#189]
tvdung94

Medium

# Weekly emission reward's amount will be less than expected in some certain cases

## Summary
Emission token will be minted weekly proportional to the number of active gauges.

The problem is that the code to determine active gauges does not take gauges, which barely meet the requirement for being active gauges, into account. Thus, the number of active gauges returned by this code is smaller than actual in some cases.

## Vulnerability Detail

The amount of emission token minted weekly is determined proportionally to the number of active gauges:

```solidity
 function weekly_emission() public view returns (uint) {
        uint256 numberOfGauges = _voter.activeGaugeNumber();
        if(numberOfGauges == 0) { 
            return weeklyPerGauge;
        }
        return weeklyPerGauge * numberOfGauges;
    }
```

`minShareForActiveGauge` is the minimum amount of shares to be considered active gauge:

```solidity
uint public minShareForActiveGauge = 1e16; // share of total rewards requried to be considired active gauge 1e18 = 100%
```
Gauges which barely have enough min share to be considered active gauges (1e16) are not counted when determining active gauges in distribute():

```solidity
if((_claimable * 1e18) / currentEpochRewardAmount > minShareForActiveGauge) {  //@audit - gauges with min shares will not be counted (==)
                activeGaugeNumber += 1;
            }
```
## Impact
Loss of rewards for users
## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Minter.sol#L98-L104

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Voter.sol#L34

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Voter.sol#L555-L557
## Tool used

Manual Review

## Recommendation
Consider including gauges which strictly have enough min share into active gauges
```solidity
 if((_claimable * 1e18) / currentEpochRewardAmount >= minShareForActiveGauge) {  
                activeGaugeNumber += 1;
            }

```

**Comment by nevillehuang** [comment]
Invalid, as described by the `minShareForActiveGauge` the gauge must have a minimum share of 1e16 (low amount given shares are denominated in 18 decimals), so no issue here
