### ISSUE TITLE
tvdung94 - `MAX_FEES` is not enforced in optionTokenV4 contract

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#190]
tvdung94

Medium

# `MAX_FEES` is not enforced in optionTokenV4 contract

## Summary
`MAX_FEES` is the maximum percentage of fees allowed to take from user payment. In the code, `MAX_FEES` is set to 50, meaning that maximum only 50% of user payment will go to fee.

The problem is that `MAX_FEES` is not respected when adding or replacing treasuries, leading to the fact that users will have to pay more than `MAX_FEES` (50%) in some certain cases.
## Vulnerability Detail
`MAX_FEES` is set to 50%
```solidity
uint256 public constant MAX_FEES = 50;
```

However, in treasury management functions, such as addTreasury() and replaceTreasury(), there is currently no check if the total percentage of fees exceeds `MAX_FEES`.

```solidity
    function addTreasury(TreasuryConfig calldata _treasury) external onlyAdmin {
        require(_treasury.treasury != address(0), 'addr 0');
        treasurys.push(_treasury);

        emit AddTreasury(_treasury.treasury, _treasury.fee, _treasury.notify);
    }

    function replaceTreasury(TreasuryConfig calldata _treasury,uint256 _pos) external onlyAdmin{
        require(_treasury.treasury != address(0), 'addr 0');
        require(_pos < treasurys.length, '_pos out of range');
        treasurys[_pos] = _treasury;
    }
```
## Impact
Users might have to pay for fees much more than intended.
## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L34
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L425-L436

## Tool used

Manual Review

## Recommendation
Consider adding a check which will revert when fees from treasuries take more than `MAX_FEES` of user payment into addTreasury() and replaceTreasury().

**Comment by nevillehuang** [comment]
Invalid, admin only functionalities to enforce fees, so invalid per sherlock [rules](https://github.com/sherlock-protocol/sherlock-v2-docs/tree/29a019b8690eb01df3587868c4d7eac1e3459bda/audits/judging/judging#vii-list-of-issue-categories-that-are-not-considered-valid)

> ii. An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue.
