### ISSUE TITLE
Filip.R - When `_sendTokenFees` is fail, `balance` may have wrong value in `swap` function.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#192]
Filip.R

Medium

# When `_sendTokenFees` is fail, `balance` may have wrong value in `swap` function.

## Summary
When `hasGauge` is `true`, `_sendTokenFees(token0, fee0)`, `_sendTokenFees(token1, fee1) `always adjusts the balance as `_balance0 = _balance0 - fee0`, `_balance1 = _balance1 - fee1`, assuming that the process is successful.

## Vulnerability Detail
The `_sendTokenFees` function runs over an external bridge, which may fail.
In this case, even though the fee transmission failed, the calculation to subtract the fee from the balance is performed.

## Impact
An error in balance calculation may cause an inconsistency in the overall `swap` function, resulting in token loss.

## Code Snippet

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Pair.sol#L318-L327

    // this low-level function should be called from a contract which performs important safety checks
    function swap(uint amount0Out, uint amount1Out, address to, bytes calldata data) external lock {
        require(!IPairFactory(factory).isPaused(address(this)),"isPaused");
        require(amount0Out > 0 || amount1Out > 0, 'IOA'); // Pair: INSUFFICIENT_OUTPUT_AMOUNT
        (uint _reserve0, uint _reserve1) =  (reserve0, reserve1);
        require(amount0Out < _reserve0 && amount1Out < _reserve1, 'IL'); // Pair: INSUFFICIENT_LIQUIDITY

        uint _balance0;
        uint _balance1;
        { // scope for _token{0,1}, avoids stack too deep errors
        (address _token0, address _token1) = (token0, token1);
        require(to != _token0 && to != _token1, 'IT'); // Pair: INVALID_TO
        if (amount0Out > 0) _safeTransfer(_token0, to, amount0Out); // optimistically transfer tokens
        if (amount1Out > 0) _safeTransfer(_token1, to, amount1Out); // optimistically transfer tokens
        if (data.length > 0) IPairCallee(to).hook(msg.sender, amount0Out, amount1Out, data); // callback, used for flash loans
        _balance0 = IERC20(_token0).balanceOf(address(this));
        _balance1 = IERC20(_token1).balanceOf(address(this));
        }
        uint amount0In = _balance0 > _reserve0 - amount0Out ? _balance0 - (_reserve0 - amount0Out) : 0;
        uint amount1In = _balance1 > _reserve1 - amount1Out ? _balance1 - (_reserve1 - amount1Out) : 0;
        require(amount0In > 0 || amount1In > 0, 'IIA'); // Pair: INSUFFICIENT_INPUT_AMOUNT
        { // scope for reserve{0,1}Adjusted, avoids stack too deep errors
        (address _token0, address _token1) = (token0, token1);

        uint fee0 = amount0In * IPairFactory(factory).getFee(address(this)) / 10000;
        uint fee1 = amount1In * IPairFactory(factory).getFee(address(this)) / 10000;

        if (hasGauge){
        @>>>    if (amount0In != 0) _sendTokenFees(token0, fee0);
        @>>>    if (amount1In != 0) _sendTokenFees(token1, fee1);
        } 

        @>>>if (amount0In != 0) _balance0 = _balance0 - fee0;
        @>>>if (amount1In != 0) _balance1 = _balance1 - fee1;
        // The curve, either x3y+y3x for stable pools, or x*y for volatile pools
        require(_k(_balance0, _balance1) >= _k(_reserve0, _reserve1), 'K'); // Pair: K
        }
        
        _balance0 = IERC20(token0).balanceOf(address(this)); 
        _balance1 = IERC20(token1).balanceOf(address(this));
        _update(_balance0, _balance1, _reserve0, _reserve1);
        emit Swap(msg.sender, amount0In, amount1In, amount0Out, amount1Out, to);
    }

## Tool used

Manual Review

## Recommendation
You must check the success of `_sendTokenFees` and accurately reflect the `fee` in the `balance` depending on success or failure.

**Comment by nevillehuang** [comment]
Invalid, transactions will revert if `_sendTokenFees` revert
