### ISSUE TITLE
pseudoArtist - Unsafe casting in RewardsDistributorV2 leads to underflow of `ve_for_at`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#195]
pseudoArtist

Medium

# Unsafe casting in RewardsDistributorV2 leads to underflow of `ve_for_at`

## Summary
Solidity does not revert when casting a negative number to uint. Instead, it underflows to a large
number. 
## Vulnerability Detail
In the `RewardDistributorV2` contract, the balance of a token at specific time is calculated as follows :

```solidity
 function ve_for_at(uint256 _tokenId, uint256 _timestamp) external view returns (uint256) {
        address ve = voting_escrow;
        uint256 max_user_epoch = IVotingEscrow(ve).user_point_epoch(_tokenId);
        uint256 epoch = _find_timestamp_user_epoch(ve, _tokenId, _timestamp, max_user_epoch);
 @>       IVotingEscrow.Point memory pt = IVotingEscrow(ve).user_point_history(_tokenId, epoch);
 @>      return Math.max(uint256(int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts))))), 0);
    }
```

This supposes to return zero when the calculated balance is a negative number. However, it underflows to a large
number. This would lead to incorrect reward distribution if third-party protocols depend on this function, or when further
updates make use of this codebase.

## Code Snippet
```solidity
 function ve_for_at(uint256 _tokenId, uint256 _timestamp) external view returns (uint256) {
        address ve = voting_escrow;
        uint256 max_user_epoch = IVotingEscrow(ve).user_point_epoch(_tokenId);
        uint256 epoch = _find_timestamp_user_epoch(ve, _tokenId, _timestamp, max_user_epoch);
 @>       IVotingEscrow.Point memory pt = IVotingEscrow(ve).user_point_history(_tokenId, epoch);
 @>      return Math.max(uint256(int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts))))), 0);
    }
```
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L134-L140

## Tool used

Manual Review

## Recommendation
Return zero for a negative number.

```solidity
int256 result = int256(pt.bias - pt.slope * int128(int256(_timestamp - pt.ts)));
if (result < 0) return 0;
return uint256(result);
```

Recommend to improve other parts of the codebase too :

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L158

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L208

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L265

**Comment by nevillehuang** [comment]
See comment [here](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/649#issuecomment-2283085297)
