### ISSUE TITLE
bughuntoor - Significant precision loss when calculating gauge's reward rate.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#211]
bughuntoor

High

# Significant precision loss when calculating gauge's reward rate.

## Summary
Significant precision loss when calculating gauge's reward rate.

## Vulnerability Detail
When calculating the gauge's reward rate, scaling is not used. Instead, the amount that is distributed is simply divided by `DURATION` in order to calculate the reward rate per second. 

```solidity
            amount = balanceAfter - balanceBefore;
            rewardRate[token] = (amount + _left) / DURATION;
```

This would cause rounding down of up to `DURATION` (604800). If the reward token for example is WBTC, this rounding down will equal to `604800 * 60_000 / 1e8 = $362` (considering btc price of $60k)

## Impact
Loss of funds

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/GaugeV4.sol#L587

## Tool used

Manual Review

## Recommendation
Use scaling when calculating the reward rate

**Comment by nevillehuang** [comment]
Invalid, per details below, precision loss will be extremely minimal. Additionally, WBTC has [18 decimals on IOTA EVM](https://explorer.evm.iota.org/token/0xfE3a7c4F992FC26c59b672284200bF2fd19F443D), and even if it is the standard 8 decimal token, the computation presented is completely wrong.

> Tokens that are used for rewards/bribes that are not part of the pool needs to be whitelisted by protocol.
