### ISSUE TITLE
Hearmen - _checkpoint_token in RewardsDistributor will revert due to overflow

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#221]
Hearmen

High

# _checkpoint_token in RewardsDistributor will revert due to overflow

## Summary
Issue High: _checkpoint_token in RewardsDistributor will revert due to overflow 

## Vulnerability Detail

In the contract RewardsDistributor.sol, the function `_checkpoint_token` will revert due to overflow, 

[RewardsDistributor](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributor.sol#L65-L97)
```solidity
    function _checkpoint_token() internal {
        uint token_balance = IERC20(token).balanceOf(address(this));
        uint to_distribute = token_balance - token_last_balance;  
        token_last_balance = token_balance;

        uint t = last_token_time; // 1653523200 
        uint since_last = block.timestamp - t; // 518400
        last_token_time = block.timestamp; // 1654041600
        uint this_week = t / WEEK * WEEK; // 1653523200
        uint next_week = 0;

        for (uint i = 0; i < 20; i++) {
            next_week = this_week + WEEK;  
            if (block.timestamp < next_week) { 
                if (since_last == 0 && block.timestamp == t) {
                    tokens_per_week[this_week] += to_distribute;
                } else {
                    tokens_per_week[this_week] += to_distribute * (block.timestamp - t) / since_last;  // block.timestamp may less than t
                }
                break;
            } else { 
                if (since_last == 0 && next_week == t) {
                    tokens_per_week[this_week] += to_distribute;
                } else {
                    tokens_per_week[this_week] += to_distribute * (next_week - t) / since_last;
                }
            }
            t = next_week;
            this_week = next_week;
        }
        emit CheckpointToken(block.timestamp, to_distribute);
    }
```

let us image `block.timestamp` is `1654041600`, `last_token_time` is `1653523200`.

before the loop , t is `1653523200`, this_week is `1653523200`, since_last is `518400`,next_week is `0`

the first round: t is `1653523200`, next_week is `1654128000`, so `block.timestamp < next_week`, 
the second round: t is `1654128000`, this_week is `1654128000`, next_week is `1654732800`,so `block.timestamp < next_week`,  and will execute `tokens_per_week[this_week] += to_distribute * (block.timestamp - t) / since_last;`.  at this time `block.timestamp` is `1654041600` which is less than t, so the sub will trigger revert due to overflow

## Impact

DOS

## Code Snippet

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributor.sol#L65-L97

## Tool used
Manual Review

## Recommendation

NAN

**Comment by nevillehuang** [comment]
Invalid, I believe the watson meant an underflow, but this is not an issue since emissions are supposed to be checkpointed weekly.
