### ISSUE TITLE
bughuntoor - Options will be impossible to be exercised in case `maxLPDiscount == minLPDiscount`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#240]
bughuntoor

Medium

# Options will be impossible to be exercised in case `maxLPDiscount == minLPDiscount`

## Summary
Options will be impossible to be exercised in case `maxLPDiscount == minLPDiscount`

## Vulnerability Detail
When calculating the slope and intercept for the discount, the following calculation is used
```solidity
    function getSlopeInterceptForLpDiscount()
        public
        view
        returns (int256 slope, int256 intercept)
    {
        slope =
            int256(lockDurationForMaxLpDiscount - lockDurationForMinLpDiscount) /
            (int256(maxLPDiscount) - int256(minLPDiscount));
        intercept = int256(lockDurationForMinLpDiscount) - (slope * int256(minLPDiscount));
    }
```

The problem arises in the situation where `maxLPDiscount == minLPDiscount`. Then, division by 0 will occur and transactions will revert. No options will be possible to be exercised into LP/ve.

## Impact
DoS

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L358

## Tool used

Manual Review

## Recommendation
If `maxLPDiscount == minLPDiscount`, return `slope == 1` and `intercept == 0`.

**Comment by nevillehuang** [comment]
Invalid, it is not reasonable for max and minimum LP discount to be the same, especially based on [default values](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/OptionTokenV4.sol#L145C1-L147C1)
