### ISSUE TITLE
bughuntoor - Changing a gauge's external bribe will brick `veNFTs` as they'll attempt withdrawing from the new one.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#241]
bughuntoor

High

# Changing a gauge's external bribe will brick `veNFTs` as they'll attempt withdrawing from the new one.

## Summary
Changing a gauge's external bribe will brick `veNFTs` as they'll attempt withdrawing from the new one.

## Vulnerability Detail
Within the `Voter` contract, admins can change a gauge's external bribe
```solidity
    function setExternalBribeFor(address _gauge, address _external) external onlyEmergencyCouncil {
        require(isGauge[_gauge]);
        _setExternalBribe(_gauge, _external);
    }

    function _setExternalBribe(address _gauge, address _external) private {
        external_bribes[_gauge] = _external;
        address pool = poolForGauge[_gauge];
        try IPair(pool).setExternalBribe(_external){} catch {}
        emit ExternalBribeSet(msg.sender, _gauge, _external);
    }
```

It must be noted that upon voting for a gauge/pool, a deposit is made into the current external bribe
```solidity
                poolVote[_tokenId].push(_pool);

                weights[_pool] += _poolWeight;
                votes[_tokenId][_pool] += _poolWeight;
                IBribe(external_bribes[_gauge])._deposit(uint256(_poolWeight), _tokenId);
```

By changing the external bribe, next time `_reset` is called, it will attempt to make a withdraw from the new external bribe
```solidity
                if (_votes > 0) {
                    IBribe(external_bribes[gauges[_pool]])._withdraw(uint256(_votes), _tokenId);
                    _totalWeight += _votes;
```

As the deposit has been made in the old one and now attempts to withdraw from the new one, it will fail.  As any calls to `_reset` will fail for said NFTs, they'll be DoS'd. 

## Impact
DoS

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Voter.sol#L221

## Tool used

Manual Review

## Recommendation
Do not allow change of external bribes

**Comment by nevillehuang** [comment]
Invalid, change in external bribes can only be called by emergency council so likely won't be arbitrarily changed. Additionally, this is part of [sherlock rules](https://github.com/sherlock-protocol/sherlock-v2-docs/tree/29a019b8690eb01df3587868c4d7eac1e3459bda/audits/judging/judging#vii-list-of-issue-categories-that-are-not-considered-valid). Worse case scenario admin can switch external bribes back so suer can pull funds
> ii. An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue.
> 8. User experience and design improvement issues: Issues that cause minor inconvenience to users where there is no material loss of funds are not considered valid. Funds are temporarily stuck and can be recovered by the administrator or owner. Also, if a submission is a design opinion/suggestion without any clear indications of loss of funds is not a valid issue.
