### ISSUE TITLE
ZanyBonzy - Gauges cannot be created or deployed on ZKsync

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#254]
ZanyBonzy

Medium

# Gauges cannot be created or deployed on ZKsync

## Summary

zkSync chain, while EVM compatible has differences in the usage of the CREATE opcode compared other EVMs.

## Vulnerability Detail
According to the contest README, the protocol is to be compatible with any EVM compatible chain (except Ethereum).
> First on IOTA EVM, but code was build with any EVM-compatible network in mind. There is no plan to deploy in on Ethereum mainnet

The [zkSync documentation](https://era.zksync.io/docs/reference/architecture/differences-with-ethereum.html#create-create2) explain how it differs from Ethereum and it states that the CREATE opcode cannot be used for arbitrary code unknown to the compiler.

In GaugeFactoryV4.sol and ProxyGaugeFactory.sol, gauge are created and deployed, using the CREATE opcode.

```solidity
    function createGauge(address _pool, address _external_bribe, address _ve, bool isPair, address[] memory allowedRewards) external returns (address) {
        last_gauge = address(new GaugeV4(_pool, _external_bribe, _ve, msg.sender, oFlow, address(this), isPair, allowedRewards));
        if (oFlow != address(0)) {
            IAccessControl(oFlow).grantRole(MINTER_ROLE, last_gauge);
        }
        return last_gauge;
    }
```

```solidity
    function deployGauge(address _notifyAddress,address _pairAddress,string memory _symbol) external onlyOwner returns (address) {
        address last_gauge = address(new ProxyGauge(flow,_notifyAddress,_symbol));
        if(_pairAddress == address(0)) {
            _pairAddress = last_gauge;
        }
        isWhitelisted[_pairAddress] = last_gauge;
        return last_gauge;
    } 
```
But, when deploying on zkSync, it is imperative that the compiler is aware of the bytecode of the deployed contract in advance. In this case, the bytecode isn't known in advance and as a result, there will be problems and reversions in gauge deployment

## Impact

Break of compatibility with zkSync EVM compatible chain, core functionalities and inability to deploy and create gauges.

## Code Snippet

https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/factories/GaugeFactoryV4.sol#L21

https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/factories/ProxyGaugeFactory.sol#L20

## Tool used
Manual Code Review

## Recommendation

Consider using CREATE2 instead and ensuring that the compiler is aware of the bytecode of the deployed contract in advance.

**Comment by nevillehuang** [comment]
Invalid, don't think this is an issue per [docs](https://docs.zksync.io/build/developer-reference/ethereum-differences/evm-instructions#create-create2)? Also zkSync was not explicitly mentioned to be supported, but if there is an issue, could be valid per [comments](https://discord.com/channels/812037309376495636/1257350045976760404/1263288657184559185)
