### ISSUE TITLE
joshuajee - Unsafe use of `_mint` instead of `_safeMint`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#264]
joshuajee

Medium

# Unsafe use of `_mint` instead of `_safeMint`

## Summary

Using `_safeMint` guarantees that the receiver address is either a smart contract that implements `IERC721Receiver.onERC721Received` or an EOA.

## Vulnerability Detail

The `_create_lock` and `split` functions use `_mint` instead of  `_safeMint`, the `_mint`  function doesn't check if the token receiver is a smart contract that can handle NFTs.

## Impact

Loss of token if minted to a smart contract that can't properly handle ERC721 tokens.

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/VotingEscrow.sol#L848
```sol
    function _create_lock(uint _value, uint _lock_duration, address _to) internal returns (uint) {
        ...
        ++tokenId;
        uint _tokenId = tokenId;
@-> _mint(_to, _tokenId);

        _deposit_for(_tokenId, _value, unlock_time, locked[_tokenId], DepositType.CREATE_LOCK_TYPE);
        return _tokenId;
    }
```

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/VotingEscrow.sol#L1242
```sol
    function split(uint _tokenId,uint amount) external {
        ...
        ++tokenId;
        uint _newTokenId = tokenId;
@-> _mint(_to, _newTokenId);
        _deposit_for(_newTokenId, amount, unlock_time, locked[_newTokenId], DepositType.SPLIT_TYPE);
    }

```

## Tool used

Manual Review

## Recommendation

Use `_safeMint` instead of  `_mint` to ensure that the token receiver can safely handle ERC721 tokens.

**Comment by nevillehuang** [comment]
Invalid per [sherlock guidelines](https://github.com/sherlock-protocol/sherlock-v2-docs/tree/29a019b8690eb01df3587868c4d7eac1e3459bda/audits/judging/judging#vii-list-of-issue-categories-that-are-not-considered-valid)

> 21. ERC721 unsafe mint: In case of a protocol implementing minting/claiming of ERC721, users being unable to do so due to incorrect implementation is not a valid issue.
