### ISSUE TITLE
tvdung94 - Exercising ve and lp will not give users 100% discount as intended

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#273]
tvdung94

High

# Exercising ve and lp will not give users 100% discount as intended

## Summary

As stated by the sponsor, when exercising option token for lp or ve, users will get 100% discount but they have to wait for a while to claim that amount (lock duration)

> when you choose exercise to LP -> veNFT
> you are getting 100% discount on the FLOW piece 

The problem is that in the current implementation, allowed discount value could only be somewhere between 20% and 80%.

## Vulnerability Detail
`_discount` could only be between minLpDiscount (80) and maxLpDiscount (20):

```solidity
uint256 public  maxLPDiscount = 20; //  User pays 20%
uint256 public  minLPDiscount = 80; //  User pays 80%

if (_discount > minLPDiscount || _discount < maxLPDiscount) 
            revert OptionToken_InvalidDiscount();
```

Therefore it cant be 100, and users still have to pay for underlying token + wait for lock to expire
## Impact
Loss of funds for users, for they have to pay at least 20% of the value (users should not have to pay).
## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L145-L146

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L602-L603
## Tool used

Manual Review

## Recommendation
Consider setting `maxLPDiscount` to 0

**Comment by nevillehuang** [comment]
Invalid, documentation error, these are admin determined values
