### ISSUE TITLE
krkba - missing _from balance check in Flow.transferFrom function

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#28]
krkba

Medium

# missing _from balance check in Flow.transferFrom function

krkbaa
## Vulnerability Detail
in Flow.sol contract the transferFrom function dosent validate the input of _from address,it doesnt check that the _from address has enough balance.
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Flow.sol#L72-L78

also the internal _transfer function doesnt do that 
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Flow.sol#L59-L66

also the User can transfer to zero address by mistake , while there is `burn` function if he need to.
## Impact
it will fail without a revert message that show the caller what was the error.
## Tool used

Manual Review

## Recommendation
add a input check with clear error message like :
```solidity
require(balanceOf[_from] >= _value, "ERC20: transfer amount exceeds balance");
```

**Comment by nevillehuang** [comment]
Invalid, an explicit check is not required, if there is insufficient amount to transfer, underflow is correct
