### ISSUE TITLE
Smacaud - Unsafe casting in RewardsDistributorV2 can lead to underflow

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#281]
Smacaud

Medium

# Unsafe casting in RewardsDistributorV2 can lead to underflow

## Summary

The RewardDistributorV2 contract uses unsafe type casting from int256 to uint256, which can lead to unexpected underflows and incorrect reward distributions

## Vulnerability Detail

Solidity doesn't revert when casting a negative int256 to uint256. Instead, it silently underflows, resulting in a large positive number. 

This can be noticed in three critical locations within the RewardDistributorV2 contract:

1. In the calculation of token balance at a specific time, [#L138-#L139)](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L138-#L139)

```diff

IVotingEscrow.Point memory pt = IVotingEscrow(ve).user_point_history(_tokenId, epoch);
  return Math.max(uint(int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts))))), 0);

```
2. In the calculation of ve_supply[t], [#L158](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L158)

```diff

ve_supply[t] = Math.max(uint(int256(pt.bias - pt.slope * dt)), 0);

```

3. In the calculation of balance_of, [#L208](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L208)

```diff

uint balance_of = Math.max(uint(int256(old_user_point.bias - dt * old_user_point.slope)), 0);

```

In all these cases, negative results are intended to be treated as zero. However, the current implementation allows negative values to underflow to large positive numbers, bypassing the Math.max() check.

## Impact

Unsafe casting can lead to incorrect reward distribution 

## Code Snippet

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L138-#L139

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L158

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L208

## Tool used

Manual Review

## Recommendation

Implement safe casting that explicitly handles negative values like this:

```diff

int256 result = int256(pt.bias - pt.slope * int128(int256(_timestamp - pt.ts)));

if (result < 0) return 0;

return uint256(result);

```

**Comment by nevillehuang** [comment]
See comment [here](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/649#issuecomment-2283085297)
