### ISSUE TITLE
krkba - malicious `voter` call to `getReward` function can claim rewards on behalf of any account.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#29]
krkba

High

# malicious `voter` call to `getReward` function can claim rewards on behalf of any account.

krkbaa
## Vulnerability Detail
The `getReward` function allows a malicious voter call to claim rewards on behalf of any account. 
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Gauge.sol#L264-L287
it can be called from `claimRewards` function in voter.sol contract
```solidity
 function claimRewards(address[] memory _gauges, address[][] memory _tokens) external {
        for (uint i = 0; i < _gauges.length; i++) {
            IGauge(_gauges[i]).getReward(msg.sender, _tokens[i]);
        }
    }
```
It passes msg.sender (the caller of claimRewards) and _tokens[i] to the getReward function.
The `claimRewards` function calls `getReward` on gauge.sol contract, passing the user (msg.sender) and _tokens.
The `getReward` function in the gauge contract allows `msg.sender` to be either the account itself or the voter.
This enables the `voter` to claim rewards on behalf of any account.
## Impact
it can lead to unauthorized access and transfer of rewards. If the voter address is compromised or malicious, it can drain rewards from any account by calling getReward for different accounts.
## Tool used

Manual Review

## Recommendation
restrict the msg.sender to only be the account itself
```solidity
require(msg.sender == account);
```
or validite the input of claimRewards function in voter.sol contract

**Comment by nevillehuang** [comment]
Invalid, rewards can only be claim for the caller represented by `msg.sender` not any arbitrary address. If an approved user can claim rewards and send to user, it is only because the owner allowed him to, no issue.
