### ISSUE TITLE
eeyore - Unused tokens are not refunded to the caller when adding liquidity in the `OptionTokenV4`.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#295]
eeyore

Medium

# Unused tokens are not refunded to the caller when adding liquidity in the `OptionTokenV4`.

## Summary

When adding liquidity, if any of the tokens are not fully utilized, they are not returned to the caller after `IRouter(router).addLiquidity()` is called.

## Vulnerability Detail

During the process of adding liquidity, the parameters `_amount` and `paymentAmountToAddLiquidity` are used as `amountADesired` and `amountBDesired`, respectively. However, there is no guarantee that the full amounts will be used.

If the liquidity is added in a different proportion, the unused tokens are never refunded to the caller.

```solidity
        (, , lpAmount) = IRouter(router).addLiquidity(
            underlyingToken,
            paymentToken,
            false,
            _amount, // <-- difference between amount used and amount provided is not refunded
            paymentAmountToAddLiquidity, // <-- difference between amount used and amount provided is not refunded
            1,
            1,
            address(this),
            block.timestamp
        );
```

## Impact

Users will overpay when calling the `exerciseLp()` and `exerciseVe()` functions.

## Code Snippet

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L626-L636
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L685-L695

## Tool used

Manual Review

## Recommendation

Refund the caller with the payment token if `paymentAmountToAddLiquidity` is not fully utilized.
If `_amount` is not fully utilized, recalculate the remaining value back to the oToken and mint it back to the user.

**Comment by nevillehuang** [comment]
Invalid, this is used as slippage, not the amount transferred as seen [here](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/Router.sol#L176)
