### ISSUE TITLE
krkba - Incorrect Calculation of `endTime`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#30]
krkba

High

# Incorrect Calculation of `endTime`

krkbaa 
## Summary
in Gauge.sol contract the `_calcRewardPerToken` function has wrong calculation of `endTime` which can lead to incorrect reward per token calculations, it can significantly impact the fairness and accuracy of reward distribution.
## Vulnerability Detail
in `_calcRewardPerToken` in `Gauge.sol` https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Gauge.sol#L344-L347

The function calculates endTime using Math.max(timestamp1, startTimestamp). This logic is flawed because it sets endTime to the greater of timestamp1 and startTimestamp, the result endTime might exceed the current reward period, leading to an incorrect calculation of the reward per token.
for example:
```solidity
// Assume rewardRate[token] = 1, periodFinish[token] = 10000, PRECISION = 1e18, and derivedSupply = 1000
uint timestamp1 = 20000; // Future timestamp
uint timestamp0 = 5000; // Past timestamp
uint supply = 1000;
uint startTimestamp = 1000; // Start timestamp

(uint rewardPerToken, uint endTime) = _calcRewardPerToken(token, timestamp1, timestamp0, supply, startTimestamp);
```
can lead to a scenario where timestamp1 is before startTimestamp. This can cause the reward calculation to be inaccurate.

`endTime` should be 1000 (the maximum of timestamp1 and startTimestamp), but it will be set incorrectly to 20000, then `rewardPerToken` will be calculated based on this incorrect endTime, resulting in an incorrect reward amount.
## Impact
when `endTime` is set incorrectly, the reward per token will be miscalculated.
## Tool used

Manual Review

## Recommendation
Change the calculation of endTime to ensure it does not exceed the reward period by using
```solidity
Math.min(timestamp1, startTimestamp)
```

**Comment by nevillehuang** [comment]
Invalid, code logic is correct, the issue is incorrectly describing the `endTime` computation. If you take endTime as the minimum, the reward computation will be completely wrong.
