### ISSUE TITLE
eeyore - Corrupted fee distribution system in the `Pair.sol` contract.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#304]
eeyore

Medium

# Corrupted fee distribution system in the `Pair.sol` contract.

## Summary

Multiple flaws have been detected in the fee distribution system within the `Pair.sol` contract, which could potentially allow the theft of all tokens from all pairs.

## Vulnerability Details

1. **Approval for Unlimited Amount of Both Pair Tokens in `setExternalBribe()` Function:**

```solidity
File: Pair.sol
120:     function setExternalBribe(address _externalBribe) external {
121:         require(msg.sender == voter, 'Only voter can set external bribe');
122:         externalBribe = _externalBribe;
123:         _safeApprove(token0, externalBribe, type(uint).max); // <=== whole current/future balance approved to external address
124:         _safeApprove(token1, externalBribe, type(uint).max); // <=== whole current/future balance approved to external address
125:         emit ExternalBribeSet(_externalBribe);
126:     }
```

The purpose of this approval is to allow the externalBribe system to claim collected fees. However, the fees collected are significantly smaller than the total `Pair` balance, and the external address should not have access to user funds.

The `setExternalBribe()` function is initially called from within the `Voter.createGauge()` function for a newly created `ExternalBribe` contract.

```solidity
File: Voter.sol
354:         address _external_bribe = IPair(_pool).externalBribe();
356:         if(_external_bribe == address(0)) {
357:           _external_bribe = IBribeFactory(bribefactory).createExternalBribe(allowedRewards);
358:         }
...
372:         if (isPair) {
373:             IPair(_pool).setHasGauge(true);
374:             IPair(_pool).setExternalBribe(_external_bribe);
375:         }
```

Although this may not seem critical at first glance, the `Voter` contract also contains a direct `Voter.setExternalBribeFor()` function.

```solidity
File: Voter.sol
143:     function setExternalBribeFor(address _gauge, address _external) external onlyEmergencyCouncil {
144:         require(isGauge[_gauge]);
145:         _setExternalBribe(_gauge, _external);
146:     }
```

Even though it is an admin-restricted function, the consequences of the emergency council wallet being compromised could lead to the extraction of all tokens from all pairs in the system, which is highly problematic.

None of the protocol's administrators should have access to user funds provided as liquidity to any Pair. These funds should be added/removed in a permissionless and trustless manner.

2. **Old ExternalBribe Address Approval Not Revoked in `setExternalBribe()` Function:**

When switching the externalBribe via the `setExternalBribe()` function, the old externalBribe address approval is not revoked.

3. **Potential Denial of Service (DoS) on Swaps in `Pair`:**

This issue arises from the fact that in the `ExternalBribe` contract, the allowed user (restricted by `require(msg.sender == IVotingEscrow(_ve).team(), 'only team');`) can change the reward tokens. If a swap is performed with one of the `Pair` tokens that is not whitelisted or if the MAX_REWARDS_TOKEN limit is reached, the `.notifyRewards()` function will revert for each swap.

```solidity
File: ExternalBribe.sol
279:     function notifyRewardAmount(address token, uint amount) external lock {
280:         require(amount > 0);
281:         if (!isReward[token]) {
282:           require(IVoter(voter).isWhitelisted(token), "bribe tokens must be whitelisted");
283:           require(rewards.length < MAX_REWARD_TOKENS, "too many rewards tokens");
284:         }
```

## Impact

Loss of all funds from all `Pair` contracts and Denial of Service (DoS) on swaps.

## Code Snippet

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Pair.sol#L120-L126
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Voter.sol#L143-L153
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Voter.sol#L354-L358
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Voter.sol#L372-L375

## Tool used

Manual Review

## Recommendation

There is no need for such approval. Consider creating an additional fee-collecting contract for each pair to which the fees will be optimistically transferred during fee collection. Only then should the ExternalBribe contract be called to collect its fees. This approach will only allow ExternalBribe to `transferFrom` the fees that were actually collected, resolving this centralization risk.

To prevent the DoS scenario, the call to collect the fees should be made from within the ExternalBribe contract, not the Pair contract.

**Comment by nevillehuang** [comment]
Invalid, 

Not a smart contract vulnerability, assuming compromised wallet
> ERC721 unsafe mint: In case of a protocol implementing minting/claiming of ERC721, users being unable to do so due to incorrect implementation is not a valid issue.

The externalBribe contract is switched, so no issue with not revoking approvals

> When switching the externalBribe via the setExternalBribe() function, the old externalBribe address approval is not revoked.

This is describing the exact purpose of the checks implemented
> If a swap is performed with one of the Pair tokens that is not whitelisted or if the MAX_REWARDS_TOKEN limit is reached, the .notifyRewards() function will revert for each swap.
