### ISSUE TITLE
eeyore - Users are able to split a veNFT into a new veNFT with an amount of 0.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#308]
eeyore

Medium

# Users are able to split a veNFT into a new veNFT with an amount of 0.

## Summary

The `split()` function lacks a check to prevent the creation of a new veNFT with a locked amount of 0. This inconsistency with the other functions in the system causes many functions to always revert when operating on such veNFTs.

## Vulnerability Detail

The issue arises because there is no check ensuring that the amount is greater than 0 in the `split()` function:

```solidity
File: VotingEscrow.sol
1217:     function split(uint _tokenId, uint amount) external {
              ...
1229:         require(value > amount, "amount > value"); // <=== missing check that amount > 0
              ...
1243:         _mint(_to, _newTokenId);
1243:         _deposit_for(_newTokenId, amount, unlock_time, locked[_newTokenId], DepositType.SPLIT_TYPE); // <=== breaking invariant, can create new veNFT with 0 amount
1244:     }
1245: 
```

If combined with `max_lock()` on such a newly created veNFT, this can cause all functions in the system that rely on the `_isApprovedOrOwner()` function (directly or indirectly) to always revert. After a week from `max_lock()`, it will always revert in:

```solidity
File: VotingEscrow.sol
912:     function max_lock(uint _tokenId) public {
                 ...
917:             if (unlock_time > _locked.end) {
918:                 require(_locked.end > block.timestamp, 'Lock expired');
919:                 require(_locked.amount > 0, 'Nothing is locked'); // <=== after a WEEK from split() will always revert here
```

To call `enable_max_lock()` on a new veNFT with 0 amount, the veNFT from which the split occurs must have `max_lock` set during the split, updating its lock end to a value that bypasses the `if (unlock_time > _locked.end)` check in the `max_lock()` function.

## Impact

Permanent DoS on all functions that depend on the `_isApprovedOrOwner()` function for given veNFT with 0 amount. 
The contract invariant that all veNFTs have a locked amount greater than 0 is broken.

## Code Snippet

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/VotingEscrow.sol#L1229
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/VotingEscrow.sol#L919

## Tool Used

Manual Review

## Recommendation

Add a check in the `split()` function to validate that `amount > 0`.

**Comment by nevillehuang** [comment]
Invalid, this is essentially user error. They can simply deposit for that specific split token Id and then reenable max_lock flag again to avoid revert
