### ISSUE TITLE
krkba - Lack of Functionality in Gauge Control Functions

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#31]
krkba

High

# Lack of Functionality in Gauge Control Functions

krkbaa
## Vulnerability Detail
in GaugePlugin.sol contract the functions `checkGaugePauseAllowance`, `checkGaugeRestartAllowance`, and `checkGaugeKillAllowance` are designed to return boolean values indicating whether a specific action (pause, restart, or kill) is allowed for a given caller and gauge. However, all these functions consistently return false regardless of input parameters. 
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/GaugePlugin.sol#L65-L84
## Impact
anything relying on these functions to determine operational permissions may be misled, as all queries will result in denial (false).
## Tool used

Manual Review

## Recommendation
add functions implimentaion

**Comment by nevillehuang** [comment]
Invalid, intended to only allow the emergency council to perform such sensitive actions as seen [here](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/Voter.sol#L380-L429)
