### ISSUE TITLE
Rozzo - Unprotected Transfer to Zero Address in VotingEscrow Contract Can Permanently Lock LP Tokens

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#314]
Rozzo

Medium

# Unprotected Transfer to Zero Address in VotingEscrow Contract Can Permanently Lock LP Tokens

## Summary

`lptokens` can get stuck due to a possible transfer to the zero address of `veNFT`.

## Vulnerability Detail

In the `VotingEscrow.sol `contract, the transferFrom function is not guarded against the `_to` address being `address(0)`, despite this being explicitly mentioned in the code comments. This allows for a hypothetical burn of the `veNFT` without going through the `_burn` function, which is invoked by both the `merge()` and `withdraw()` functions.

## Impact

If an NFT containing LP tokens is transferred to the zero address, those LP tokens would effectively be locked forever. The protocol seems designed to lock tokens for a period, with specific mechanisms for unlocking (withdraw) or combining (merge). Allowing transfers to the zero address bypasses these mechanisms. This also could lead to discrepancies between the actual circulating supply and what's reported by the contract, as the NFT would technically still exist but be inaccessible, causing misleading total supply information.

## Code Snippet

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/VotingEscrow.sol#L315

## Tool used

Manual Review

## Recommendation

Add a explicit check so `_to` address is not zero.

**Comment by nevillehuang** [comment]
Invalid, based on [sherlock rules](https://github.com/sherlock-protocol/sherlock-v2-docs/tree/29a019b8690eb01df3587868c4d7eac1e3459bda/audits/judging/judging#vii-list-of-issue-categories-that-are-not-considered-valid)

> 3. Zero address checks: Check to make sure input values are not zero addresses.
