### ISSUE TITLE
bbl4de - `GaugeFactoryV4::createGauge()` lacks proper access control

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#319]
bbl4de

High

# `GaugeFactoryV4::createGauge()` lacks proper access control

## Summary
The `createGauge()` function in `GaugeFactoryV4` contract is intended to be called by the `Voter::createGauge()` function. Due to lack of `msg.sender` validation the gauge factory function may be called directly providing an opportunity to deploy a malicious `GaugeV4` contract and granting it the `MINTER_ROLE` for `oFLOW` token.
## Vulnerability Detail
Lack of modifiers / `msg.sender` validation in `GaugeFactoryV4::createGauge()`:
```solidity
function createGauge(
        address _pool,
        address _external_bribe,
        address _ve,
        bool isPair,
        address[] memory allowedRewards
    ) external returns (address) {
        last_gauge = address(
            new GaugeV4(
                _pool,
                _external_bribe,
                _ve,
                msg.sender,
                oFlow,
                address(this),
                isPair,
                allowedRewards
            )
        );
        if (oFlow != address(0)) {
            IAccessControl(oFlow).grantRole(MINTER_ROLE, last_gauge);
        }
        return last_gauge;
    }
```
Provided `_pool`, `_externalBribe` and `_ve` addresses may be of maliciously implemented contracts, and the execution itself could be done by a call from a *fake* `Voter` contract - to use `msg.sender` from the constructor argument as a voter in the created gauge.
## Impact
This will allow the owner of these contracts to fully control `GaugeV4::getReward()` function implementation and mint arbitrary amount of `oFLOW`.
## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/factories/GaugeFactoryV4.sol#L20-L26
## Tool used
Manual Review
## Recommendation
Add access control for the `GaugeFactoryV4::createGauge()` function - initially the deployer, and a setter to change the privileged address to the `Voter` contract - when it's later deployed.

**Comment by nevillehuang** [comment]
Invalid, gauges are meant to be permisionless with caveats. Although it seems like a malicious pool can be inputted i.e. whitelist not checked by pass checks in `Voter.createGauge()`.  Important state variables will not be [assigned so the gauge is unusable anyways](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/Voter.sol#L361-L367)
> Any users can create gauge for pools with whitelisted tokens on one side. (Permissionless gauge creation) Otherwise, gauge for pools without whitelisted tokens can only be created by protocol.
