### ISSUE TITLE
krkba - No Allowance Check in _safeTransferFrom function.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#32]
krkba

High

# No Allowance Check in _safeTransferFrom function.

krkbaa
## Vulnerability Detail
in OptionTokenV4.sol contract the _safeTransferFrom function does not verify if the from address has granted sufficient allowance to this contract to transfer tokens on its behalf.
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L762-L778
## Impact
it can lead to unauthorized token transfers.
## Tool used

Manual Review

## Recommendation
ensure that _from has approved this contract to transfer tokens on its behalf. rs.

**Comment by nevillehuang** [comment]
Invalid, this is implicit checked in the eventual call to `transferFrom` [here](https://github.com/transmissions11/solmate/blob/e0e9ff05d8aa5c7c48465511f85a6efdf5d5c30d/src/tokens/ERC20.sol#L97), in which it will revert if insufficient allowance is given by the user
