### ISSUE TITLE
talfao - Typecasting from int to uint Breaks Intended Behavior Inside Max(...) Leading to Rounding Down of Rewards Summary

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#322]
talfao

Medium

# Typecasting from int to uint Breaks Intended Behavior Inside Max(...) Leading to Rounding Down of Rewards Summary

## Summary
There is a wrong assumption in various `Math.max` functions where an `int` is typecast to `uint`, which will always be higher than zero. This is the main problem inside `RewardDistributorV2` in the calculation of `_checkpoint_total_supply()`.

## Vulnerability Detail
The problem arises in the `_checkpoint_total_supply` function during the storing of voting escrow points supply:

```solidity
ve_supply[t] = Math.max(uint(int256(pt.bias - pt.slope * dt)), 0);
```

In cases where `pt.bias - pt.slope * dt` results in a negative `int256`, casting it to `uint256` results in a very large positive number, whereas it **should be zero.** This can happen in rare cases when `pt.slope * dt` is greater than `pt.bias`.

For example:
```solidity
uint a = uint(int256(-1));
a -> 115792089237316195423570985008687907853269984665640564039457584007913129639935
```

## Impact
Due to this problem, `ve_supply` for the epoch will contain an enormous number, making the distribution of rewards almost negligible. Rewards are calculated as follows:

```solidity
to_distribute += balance_of * tokens_per_week[week_cursor] / ve_supply[week_cursor]
```

When `ve_supply` is very high, the reward distribution rounds down to zero. This issue also arises in other places, but it is most severe here.

## Code Snippet
[checkpoint_total_supply function](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L158)

## Tool Used
Manual Review

## Recommendation
Perform the `max` function before typecasting to `uint`. For example:

```solidity
int256 adjustedValue = pt.bias - pt.slope * dt;
ve_supply[t] = adjustedValue > 0 ? uint256(adjustedValue) : 0;
```

**Comment by nevillehuang** [comment]
See comment [here](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/649#issuecomment-2283085297)
