### ISSUE TITLE
krkba - Missing Revocation Logic in  `setTeam` function

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#33]
krkba

High

# Missing Revocation Logic in  `setTeam` function

krkbaa
## Vulnerability Detail
in Minter.sol contract the `setTeam` function does not include logic to revoke access for the old team address before assigning a new team address.
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Minter.sol#L64-L67
## Impact 
Without revoking access, the old team address is still have access to the only team functions, This could lead to unauthorized changes or misuse of contract functionality.
## Tool used

Manual Review

## Recommendation
To mitigate this issue, the `setTeam` function should have revocation of access for the old team address before assigning a new team address. This ensures that only the newly designated team has privileged access.

**Comment by nevillehuang** [comment]
Invalid, once `team` is changed, all relevant functionalities can no longer be called due to access control checks
