### ISSUE TITLE
Smacaud - Optimizer bug in Solidity versions 0.8.13

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#334]
Smacaud

Medium

# Optimizer bug in Solidity versions 0.8.13

## Summary

An optimizer bug in Solidity 0.8.13 may incorrectly remove memory write operations in inline assembly under specific conditions.

## Vulnerability Detail

The codebase heavily relies on solidity 0.8.13  which makes it vulnerable to the Optimizer bug. 

According to this [blog,](https://soliditylang.org/blog/2022/06/15/solidity-0.8.15-release-announcement), it states that "optimizer bug affects only versions 0.8.13 and 0.8.14......." 

Also, while explaining the bug is states "..... is an optimizer bug that can lead to memory write operations in inline assembly being removed if the result of such an operation is not read back from within the same assembly block. The bug can be triggered only when using the default legacy compiler pipeline (the new compilation pipeline via IR is not affected) and happens only in assembly blocks that never access Solidity variables defined in the surrounding code."

When you look at the [OptionTokenV4](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L4-#L7
), you will notice it inherits solidity contracts from openzeppelin and solmate of which both of these uses the inline assembly while optimization is enabled during compiling thereby increasing the likelihood of this bug being triggered

## Impact

This may lead to serious issues when triggered

## Code Snippet

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L4-#L7

## Tool used

Manual Review

## Recommendation

Update to higher or latest version of Solidity

**Comment by nevillehuang** [comment]
Invalid, the issue presented is extremely arbirtray and does not show how it specifically impacts the protocol code logic
