### ISSUE TITLE
DanielWang8824 - Unsafe casting in RewardsDistributorV2 leads to underflow of ve_for_at

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#337]
DanielWang8824

High

# Unsafe casting in RewardsDistributorV2 leads to underflow of ve_for_at

## Summary
Solidity does not revert when casting a negative number to uint. Instead, it underflows to a large number. Unsafe casting in RewardsDistributorV2contract leads to underflow of `ve_for_at`

## Vulnerability Detail

In RewardsDistributorV2.sol, there is ve_for_at function.

```solidity
function ve_for_at(uint _tokenId, uint _timestamp) external view returns (uint) {
    address ve = voting_escrow;
    uint max_user_epoch = IVotingEscrow(ve).user_point_epoch(_tokenId);
    uint epoch = _find_timestamp_user_epoch(ve, _tokenId, _timestamp, max_user_epoch);
    IVotingEscrow.Point memory pt = IVotingEscrow(ve).user_point_history(_tokenId, epoch);
    return Math.max(uint(int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts))))), 0);
}
```

This supposes to return zero when the calculated balance is a negative number. However, it underflows to a large number.
This would lead to incorrect reward distribution if third-party protocols depend on this function, or when further updates make use of this codebase.

## Impact
This would lead to incorrect reward distribution if third-party protocols depend on this function, or when further updates make use of this codebase.

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L139

https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L158

https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L208

https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L265

## Tool used

Manual Review

## Recommendation
We could switch Math.max and uint casting order.
```diff
- Math.max(uint(int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts))))), 0);
+ uint(Math.max(int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts)))), 0));
```

**Comment by nevillehuang** [comment]
See comment [here](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/649#issuecomment-2283085297)
