### ISSUE TITLE
krkba - No Access Control in `setVoter` function.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#34]
krkba

Medium

# No Access Control in `setVoter` function.

krkbaa
## Vulnerability Detail
in Pair.sol contract the `setVoter` function allowing any address to call it. This means any user can change the voter address to any value returned by the IPairFactory(factory).voter() call, which could be manipulated or redirected by a compromised or malicious factory contract.
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Pair.sol#L100-L102

## Impact
anyone can call `setVoter` and potentially manipulate the voter address if the factory contract is compromised.
## Tool used

Manual Review

## Recommendation
restrict access to the `setVoter` function.

**Comment by nevillehuang** [comment]
Invalid, assignment of voter is correctly accessed controlled in the PairFactory contract [here](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/factories/PairFactory.sol#L43-L48)
