### ISSUE TITLE
krkba - Missing Implementation of `getReward` Function

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#35]
krkba

High

# Missing Implementation of `getReward` Function

krkbaa
## Vulnerability Detail
the function body is empty, meaning that calling this function will not result in any action or reward distribution.
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/ProxyGauge.sol#L48-L50
## Impact
The reward mechanism will be incomplete, which could disrupt the overall incentive structure of the platform.
## Tool used

Manual Review

## Recommendation
Implement the getReward function to ensure it correctly distributes rewards.

**Comment by nevillehuang** [comment]
Invalid, no impact, also this is a proxy, which will delegate call to the implementation Gauge contracts where the relevant function is implemented
