### ISSUE TITLE
krkba - Improper Use of `assert` for Input Validation in `checkpoint_token` Function

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#36]
krkba

Medium

# Improper Use of `assert` for Input Validation in `checkpoint_token` Function

krkbaa
## Vulnerability Detail
in RewardsDistributor.sol contract the `checkpoint_token` function uses the assert statement to validate that the msg.sender is equal to the depositor
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributor.sol#L98-L101
If an assert statement fails, it consumes all the gas provided to the transaction, which can be very costly
## Impact
loss of funds (gas costs) for the caller.
## Tool used

Manual Review

## Recommendation
Replace the `assert` statement with a `require` statement to properly handle input validation.

**Comment by nevillehuang** [comment]
Invalid per [sherlock guidelines](https://github.com/sherlock-protocol/sherlock-v2-docs/tree/29a019b8690eb01df3587868c4d7eac1e3459bda/audits/judging/judging#vii-list-of-issue-categories-that-are-not-considered-valid)

> 1. Gas optimizations: The user/protocol ends up paying a little extra gas because of this issue.
