### ISSUE TITLE
mike-watson - Unreachable Code in Reset Function

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#361]
mike-watson

Medium

# Unreachable Code in Reset Function

## Summary
There's an unreachable else branch in the _reset function due to the use of unsigned integers.

## Vulnerability Detail
In the _reset function:
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Voter.sol#L220-L225

## Impact
* Unnecessary code that may confuse developers
*  misunderstanding the function's behavior

## Tool used

Manual Review

## Recommendation
Remove the unreachable else branch:
```solidity
if (_votes > 0) {
    IBribe(external_bribes[gauges[_pool]])._withdraw(_votes, _tokenId);
    _totalWeight += _votes;
}
```

**Comment by nevillehuang** [comment]
Invalid, at most gas optimization, which is a non-acceptable severity based on [sherlock rules](https://github.com/sherlock-protocol/sherlock-v2-docs/tree/29a019b8690eb01df3587868c4d7eac1e3459bda/audits/judging/judging#vii-list-of-issue-categories-that-are-not-considered-valid)

> 1. Gas optimizations: The user/protocol ends up paying a little extra gas because of this issue.
