### ISSUE TITLE
phoenixv110 - Chance of Minter losing access to mint in Flow contract

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#362]
phoenixv110

Medium

# Chance of Minter losing access to mint in Flow contract

## Summary
The **setMinter()** checks if the caller is minter and sets the same variable to the input. If a wrong address is set by mistake then the ability to **mint()** will be lost.

## Vulnerability Detail
The following function sets minter address. In case a wrong address is set then the access the **mint()** will be lost.
```solidity
function setMinter(address _minter) external {
    require(msg.sender == minter);
    minter = _minter;
}
```

## Impact
Nobody will be able to **mint()** further tokens as it checks if the caller is **minter**.
```solidity
function mint(address account, uint amount) external returns (bool) {
    require(msg.sender == minter);
    _mint(account, amount);
    return true;
}
```
## Tool used

Manual Review

## Reference code
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Flow.sol#L27-L30

## Recommendation
Implement a 2 step process to update minter address.
```solidity
address public newMinter;

function setMinter(address _minter) external {
    require(msg.sender == minter);
    newMinter = _minter;
}

function claimMinter() external {
    require(msg.sender == newMinter);
    minter = newMinter;
}
```

**Comment by nevillehuang** [comment]
Invalid, admin/user input not valid based on sherlock [rules, see point 4 and 5](https://github.com/sherlock-protocol/sherlock-v2-docs/tree/29a019b8690eb01df3587868c4d7eac1e3459bda/audits/judging/judging#vii-list-of-issue-categories-that-are-not-considered-valid)
