### ISSUE TITLE
krkba - Missing Access Control in `createGauge` Function

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#38]
krkba

High

# Missing Access Control in `createGauge` Function

krkbaa
## Vulnerability Detail
in GaugeFactoryV4.sol contract the `createGauge` function lacks proper access control mechanisms, and does not validate the input parameters, allowing any external account to call it and create new GaugeV4 instances. This omission poses a security risk as unauthorized users could potentially abuse the system by creating unnecessary gauges or consuming excessive resources.
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/factories/GaugeFactoryV4.sol#L20-L26
## Impact
abuse the system by creating unnecessary gauges or consuming excessive resources.
## Tool used

Manual Review

## Recommendation
implement an access control mechanism to restrict who can call `createGauge` function

**Comment by nevillehuang** [comment]
Invalid `createGauge()` is meant to be permisionless, in which only whitelisted tokens on one side is allowed to be created.

> Any users can create gauge for pools with whitelisted tokens on one side. (Permissionless gauge creation) Otherwise, gauge for pools without whitelisted tokens can only be created by protocol.
