### ISSUE TITLE
bin2chen - notifyRewardAmount() rewardRate is not precise enough.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#381]
bin2chen

Medium

# notifyRewardAmount() rewardRate is not precise enough.

## Summary
The `rewardRate` calculation uses `amount / 604800`.
No additional precision is added, which may result in insufficient precision and loss of some `tokens`.
## Vulnerability Detail
`GaugeV4.notifyRewardAmount()`
User gets `rewards`, and refines `rewardRate[token]`
```solidity
    function notifyRewardAmount(address token, uint amount) external lock {
...
        if (block.timestamp >= periodFinish[token]) {
            uint256 balanceBefore = IERC20(token).balanceOf(address(this));
            _safeTransferFrom(token, msg.sender, address(this), amount);
            uint256 balanceAfter = IERC20(token).balanceOf(address(this));
            amount = balanceAfter - balanceBefore;
@>          rewardRate[token] = amount / DURATION;
        } else {
```

Using the formula: `rewardRate[token] = amount / DURATION = amount / 604800`. 

Not improving the precision e.g. `amount * 1e18 / DURATION`.

This way, if the decimals of the token is low, some of the token will be lost.

Example：
1. usdc = 1000e6
lose： 1000e6 - (1000e6 / 604800) * 604800 = 265600 = $ 0.2

2. btc = 1e8
lose： 1e8 - (1e8 / 604800) * 604800 = 208000   （value：208000 * $64048 / 1e8 = $133）

Note.
This issue is not obvious in V3. (may one week)
However, in V4, due to the new `OptionToken4.sol`, which adds `paymentToken` as a reward, each `exerciseXX()` may trigger `gauge.notifyRewardAmount()`, which makes this issue more obvious.

## Impact

rewardRate is not precise enough, so some of the `tokens` are not captured and left in a reasonable amount.

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/GaugeV4.sol#L578
## Tool used

Manual Review

## Recommendation

Increase precision

`rewardRate[token] = amount * PRECISION / DURATION `

**Comment by nevillehuang** [comment]
Invalid, reward tokens should be registered by admin with this in mind, and most if not all tokens have 18 decimals on iota evm/other chains, given mainnet is not supported
