### ISSUE TITLE
MSaptarshi - Unsafe casting in RewardsDistributorV2 leads to underflow of `ve_for_at`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#392]
MSaptarshi

Medium

# Unsafe casting in RewardsDistributorV2 leads to underflow of `ve_for_at`

## Summary
Solidity does not revert when casting a negative number to uint. Instead, it underflows to a large number.
In RewardDistributorV2
`Math.max(uint(int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts))))), 0);`

## Vulnerability Detail
This supposes to return zero when the calculated balance is a negative number. However, it underflows to a large
number.
This would lead to incorrect reward distribution 
```solidity

    function ve_for_at(uint _tokenId, uint _timestamp) external view returns (uint) {
        address ve = voting_escrow;
        uint max_user_epoch = IVotingEscrow(ve).user_point_epoch(_tokenId);
        uint epoch = _find_timestamp_user_epoch(ve, _tokenId, _timestamp, max_user_epoch);
        IVotingEscrow.Point memory pt = IVotingEscrow(ve).user_point_history(_tokenId, epoch);
        return Math.max(uint(int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts))))), 0);
}
```
## Impact
incorrect Reward Distribution

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L139

## Tool used
Manual Review

## Recommendation
```solidity
int256 result = int256(pt.bias - pt.slope * int128(int256(_timestamp - pt.ts)));
if (result < 0) return 0;
return uint256(result)
```

**Comment by nevillehuang** [comment]
See comment [here](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/649#issuecomment-2283085297)
