### ISSUE TITLE
0xpiken - The lpTokens purchased through `exerciseVe()` and `exerciseLp()` might be locked longer or shorter than expected

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#399]
0xpiken

Medium

# The lpTokens purchased through `exerciseVe()` and `exerciseLp()` might be locked longer or shorter than expected

## Summary
The parameters used to calculate `duration` for a given `_discount` in the function [`getLockDurationForLpDiscount()`](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L340-L345) could be changed at any time, resulting in the `duration` being different from what was expected.

## Vulnerability Detail
- A OptionToken owner can call `exerciseVe()` or `exerciseLp()` to buy underlying token at a specified discount
- Then the purchased underlying token will be deposited into `router` together with the caller's paymentToken for lpTokens.
- The lpTokens will be locked for a specified period, which can be withdrawn only when the locking time is expired.
The duration of locking is calculated as below:
```solidity
    function getLockDurationForLpDiscount(
        uint256 _discount
    ) public view returns (uint256 duration) {
        (int256 slope, int256 intercept) = getSlopeInterceptForLpDiscount();
        duration = _discount == 0 ? lockDurationForMaxLpDiscount : SignedMath.abs(slope * int256(_discount) + intercept);
    }
    function getSlopeInterceptForLpDiscount()
        public
        view
        returns (int256 slope, int256 intercept)
    {
        slope =
            int256(lockDurationForMaxLpDiscount - lockDurationForMinLpDiscount) /
            (int256(maxLPDiscount) - int256(minLPDiscount));
        intercept = int256(lockDurationForMinLpDiscount) - (slope * int256(minLPDiscount));
    }
```
As we can see, the calculated duration result remains unchanged for the same `_discount` as long as all four parameters(`lockDurationForMaxLpDiscount`, `lockDurationForMinLpDiscount`, `maxLPDiscount` and `minLPDiscount`) in formula are kept unchanged. 

However, if any one of the four parameters is changed by admin after the `exerciseVe()` or `exerciseLp()` transaction is submitted but not mined, the locking duration might differ from what the caller expected.

## Impact
The lpTokens purchased through `exerciseVe()` and `exerciseLp()` might be locked longer or shorter than expected
## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L340-L345
## Tool used

Manual Review

## Recommendation
`minDuration` and `maxDuration` should be introduced into `exerciseVe()` and `exerciseLp()` as duration slippage protection. The transaction should revert if the calculated duration is less than `minDuration` or above than `maxDuration`.

**Comment by nevillehuang** [comment]
Invalid part of [sherlock rules](https://github.com/sherlock-protocol/sherlock-v2-docs/tree/29a019b8690eb01df3587868c4d7eac1e3459bda/audits/judging/judging#vii-list-of-issue-categories-that-are-not-considered-valid). 
> An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue
