### ISSUE TITLE
Hajime - Unsafe casting in RewardsDistributorV2

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#400]
Hajime

Medium

# Unsafe casting in RewardsDistributorV2

## Summary
When a negative number is cast to a uint, it underflows to a large number instead of returning zero as it should. This leads to incorrect reward distribution when third-party protocols depend on this function, or when further updates make use of this codebase.

## Vulnerability Detail
Solidity does not revert when a negative number is cast to uint. 
Contract, the balance of a token at specific time is calculated as follows
```solidity
 IVotingEscrow.Point memory pt = IVotingEscrow(ve).user_point_history(_tokenId, epoch);
 return Math.max(uint(int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts))))), 0);
```
This is supposed to return zero if the calculated balance is a negative number. This would lead to incorrect bounty distribution if third party protocols depended on this function, or if further updates made use of this code base.

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L138-L139
## Tool used

Manual Review

## Recommendation
```solidity
int256 result = int256(pt.bias - pt.slope * int128(int256(_timestamp - pt.ts)));
if (result < 0) return 0;
return uint256(result);
```

**Comment by nevillehuang** [comment]
See comment [here](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/649#issuecomment-2283085297)
