### ISSUE TITLE
Hajime - reaching the `_deadline` does not count

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#404]
Hajime

Medium

# reaching the `_deadline` does not count

## Summary
reaching the deadline does not count
## Vulnerability Detail
In `exercise`, `exerciseLp`, `exerciseVe`, block.timestamp must be greater than the deadline for an error to be raised. However, it is worth including the deadline timestamp itself. Since reaching the deadline itself means that the given time for `exerciseLp` has been exhausted
## Impact
reaching the deadline must be error
## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L275

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L293

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L312

## Tool used

Manual Review

## Recommendation
use `block.timestamp>=_deadline`

**Comment by nevillehuang** [comment]
Invalid, no issue here, you cannot exercise options once deadline has passed, but can still do so at the point of the deadline. It is at most a 1 second difference.
