### ISSUE TITLE
bareli - transferFrom uses allowance even if spender == from

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#405]
bareli

Medium

# transferFrom uses allowance even if spender == from

## Summary
Pool#transferFrom attempts to use allowance even when spender = from. This breaks compatibility with a large number of protocol who opt to use the transferFrom method all the time (pull only) instead of using both transfer and transferFrom (push and pull). The ERC20 standard only does an allowance check when spender != from. The result of this difference will likely result in tokens becoming irreversibly stranded across different protocols.
## Vulnerability Detail
 function transferFrom(address _from, address _to, uint _value) external returns (bool) {
        uint allowed_from = allowance[_from][msg.sender];
        if (allowed_from != type(uint).max) {
            allowance[_from][msg.sender] -= _value;
        }
        return _transfer(_from, _to, _value);
    }

The trasnferFrom method shown above always uses allowance even if spender = from.
## Impact
Token won't be compatible with some protocols and will end up stranded
## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Flow.sol#L74
## Tool used

Manual Review

## Recommendation
  @>> if (allowed_from != type(uint).max && from!=msg.sender)  {

**Comment by nevillehuang** [comment]
Invalid, the owner of the token can always provide the required allowance via `approve()` so no issue here
