### ISSUE TITLE
bareli - rewards length may cross "MAX_REWARD_TOKENS"

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#410]
bareli

Medium

# rewards length may cross "MAX_REWARD_TOKENS"

## Summary
in the constructor, we are adding rewards tokens in _allowedRewardTokens.There is no check whether the reward length is greater than MAX_REWARD_TOKENS.
## Vulnerability Detail
 constructor(address _stake, address _external_bribe, address  __ve, address _voter, address _oFlow, address _gaugeFactory, bool _forPair, address[] memory _allowedRewardTokens) {
        stake = _stake;
        external_bribe = _external_bribe;
        _ve = __ve;
        voter = _voter;
        oFlow = _oFlow;
        gaugeFactory = _gaugeFactory;
        isForPair = _forPair;
        flow = IVotingEscrow(_ve).baseToken();
        _safeApprove(flow, oFlow, type(uint256).max);

        for (uint i; i < _allowedRewardTokens.length; i++) {
            if (_allowedRewardTokens[i] != address(0)) {
                isReward[_allowedRewardTokens[i]] = true;
          @>>      rewards.push(_allowedRewardTokens[i]);
            }
        }
    }
## Impact
there is no limit to reward length. we can increase the length and our rewards length increases than the MAX_REWARD_TOKENS.
## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Gauge.sol#L103
## Tool used

Manual Review

## Recommendation
   for (uint i; i < _allowedRewardTokens.length; i++) {
            if (_allowedRewardTokens[i] != address(0)) {
                isReward[_allowedRewardTokens[i]] = true;
              rewards.push(_allowedRewardTokens[i]);
             @>>           require(rewards.length < =MAX_REWARD_TOKENS, "too many rewards tokens");

**Comment by nevillehuang** [comment]
Low severity, since gauges deployed via factory is deployed by the admin. Any other gauges must be craeted via the Voter.sol contract to be usable
