### ISSUE TITLE
igor101286 - Improper Handling of balanceWithLock and lockEnd

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#414]
igor101286

High

# Improper Handling of balanceWithLock and lockEnd

## Summary
The depositWithLock function in the GaugeV4 contract allows users to deposit funds with a lock period. However, the current implementation contains vulnerabilities related to handling multiple locks and incorrect validation of balanceWithLock and lockEnd during withdrawals. This can lead to bypassing the lock mechanism, compromising the security of user funds.
## Vulnerability Detail
The depositWithLock function allows users to deposit funds with a specified lock duration. However, the implementation does not handle scenarios where multiple locks are added sequentially. In the current implementation, if a user makes multiple deposits with locks, it can result in incorrect handling of the lock end time and the amount of locked funds.

Additionally, during the withdrawal process, the contract does not always correctly check if the lock period has expired. If the amount to withdraw exceeds the free balance (considering the locked funds), the contract does not properly verify if the lock period has expired, allowing users to bypass the lock mechanism and withdraw funds before the lock expires.

`function depositWithLock(address account, uint256 amount, uint256 _lockDuration) external lock {
    require(msg.sender == account || isOToken[msg.sender],"Not allowed to deposit with lock"); 
    _deposit(account, amount, 0);

    if(block.timestamp >= lockEnd[account]) {
        delete lockEnd[account];
        delete balanceWithLock[account];
    }

    balanceWithLock[account] += amount;
    uint256 currentLockEnd = lockEnd[account];
    uint256 newLockEnd = block.timestamp + _lockDuration ;
    if (currentLockEnd > newLockEnd) {
        revert("The current lock end > new lock end");
    } 
    lockEnd[account] = newLockEnd;
}`

Example Scenario
A user deposits 100 tokens with a lock period of 30 days.
After 15 days, the user deposits another 50 tokens with a lock period of 30 days.
The current implementation updates lockEnd to the new lock period, ignoring the remaining 15 days of the previous lock.

`function withdrawToken(uint amount, uint tokenId) public lock {
    _updateRewardForAllTokens();

    uint256 totalBalance = balanceOf[msg.sender];
    uint256 lockedAmount = balanceWithLock[msg.sender];
    uint256 freeAmount = totalBalance - lockedAmount;
    // Update lock related mappings when withdraw amount greater than free amount
    if (amount > freeAmount) {
        // Check if lock has expired
        require(block.timestamp >= lockEnd[msg.sender], "The lock didn't expire");
        uint256 newLockedAmount = totalBalance - amount;
        if (newLockedAmount == 0) {
            delete lockEnd[msg.sender];
            delete balanceWithLock[msg.sender];
        } else {
            balanceWithLock[msg.sender] = newLockedAmount;
        }
    }

    totalSupply -= amount;
    balanceOf[msg.sender] -= amount;
    _safeTransfer(stake, msg.sender, amount);
    ...
}
`

## Impact

If a user can bypass the lock mechanism, it allows premature withdrawal of locked funds, undermining user trust and compromising funds that are supposed to be secure until a certain time. This weakens the core functionality of the contract and can lead to significant financial losses.

## Code Snippet
[https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/GaugeV4.sol#L443](url)

## Tool used

Manual Review

## Recommendation

Improved Handling of Multiple Locks
Consider using a data structure, such as an array or mapping, to store multiple locks to correctly handle multiple deposits with locks. This will account for all active locks and correctly compute the final lock end time and locked amounts.

Improved Lock Validation during Withdrawal
Ensure that the lock expiration check is performed correctly, and only funds that are not under lock can be withdrawn before the lock period ends.

**Comment by duncan4123** [comment]
The first lock has still increased by 15 days in the example.

**Comment by nevillehuang** [comment]
Invalid, no issue here, logic is correct, given the new lock Time of the existing balance locked should be respected
