### ISSUE TITLE
Hajime - `amountOutMin` for intermediate, not final amount

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#420]
Hajime

High

# `amountOutMin` for intermediate, not final amount

## Summary
`amountOutMin is useless to the user

## Vulnerability Detail
A swap can execute multipleoperations before returning the final amount of tokens to the user. 
`swapExactTokensForTokenSimple`, `swapExactTokensForTokens`  in Router.sol  call `_swap` => `Pair.swap()` , in which funds are sent to the user , already without slippage control, since `amountOutMin` only applies to the transferFrom in functions of Router.sol. Since amounts is skimmed of the contract the user  no longer  ha s any way to protect  themselves from slippage
## Impact

`amountOutMin is useless to the user in Pair.swap(). If the `amountOutMin` is used for an intermediate operation but not to check the final amount, this can result in a loss of funds vulnerability for the user since they may receive fewer tokens than specified.

## Code Snippet 

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Router.sol#L352-L354

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Router.sol#L367-L369

## Tool used

Manual Review

## Recommendation
Use `amountOutMin` additionally in `Pair.swap()` when sending funds to the user

**Comment by nevillehuang** [comment]
Invalid, there is no issue here, slippage checked [here](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Router.sol#L352)
