### ISSUE TITLE
jovi - Rewards may be lost if batchRewardPerToken is not called frequently

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#424]
jovi

Medium

# Rewards may be lost if batchRewardPerToken is not called frequently

## Summary
If a everyone misses or forgets to call batchRewardPerToken for more than 7 days, rewards may be lost.
## Vulnerability Detail
The batchRewardPerToken function updates the rewardPerTokenStored stored by doing the following calculation:
```solidity
function _calcRewardPerToken(address token, uint timestamp1, uint timestamp0, uint supply, uint startTimestamp) internal view returns (uint, uint) {
        uint endTime = Math.max(timestamp1, startTimestamp);
        
        return (((Math.min(endTime, periodFinish[token]) - Math.min(Math.max(timestamp0, startTimestamp), periodFinish[token])) * rewardRate[token] * PRECISION / supply), endTime);
    }
```
The issue with that is the rewardRate mapping is the latest rewardRate stored at the contract and not necessarily corresponds to the rewardRate available during the supply checkpoint that preceded this `calcRewardPerToken` call:
```solidity
function _batchRewardPerToken(address token, uint maxRuns) internal returns (uint, uint) {
...
for (uint i = _startIndex; i < _endIndex; i++) {
            SupplyCheckpoint memory sp0 = supplyCheckpoints[i];
            if (sp0.supply > 0) {
                SupplyCheckpoint memory sp1 = supplyCheckpoints[i+1];
                (uint _reward, uint _endTime) = _calcRewardPerToken(token, sp1.timestamp, sp0.timestamp, sp0.supply, _startTimestamp);
                reward += _reward;
                _writeRewardPerTokenCheckpoint(token, reward, _endTime);
                _startTimestamp = _endTime;
            }
        }
...
}
```

Actually, if no rewardRate update is executed, the contract can keep running with the same rates ad aeternum. 
## Impact
If the batchRewardToken call is skipped during a period in which the rewardRate is higher, then someone can call this function when the rewardRate is smaller and the token earns much less rewards per unit.

Users can wait till the reward rate becomes very high to claim inflated values. The calcRewardPerToken internal function will return the amount of reward tokens per supply checkpoint based on the rewardPerToken mapping. However this mapping is not timestamp-tied. So if the rewardPerToken is super low at a point, a malicious party could call batchRewardPerToken to really damage the pool. The opposite behavior is also possible, by waiting till the rewardPerToken variable is set to a high value. 

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/GaugeV4.sol#L320

## Tool used

Manual Review

## Recommendation
Make sure to update both the rewardPerToken and the rewardRate mappings simultaneously. This way there's no chance of mapping desyncing.

**Comment by nevillehuang** [comment]
Invalid, rewardRate is fixed weekly once rewards are notifed as seen [here](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/GaugeV4.sol#L578)
