### ISSUE TITLE
jovi - _exerciseVe utilizes wrong flow to distribute gauge rewards

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#431]
jovi

Medium

# _exerciseVe utilizes wrong flow to distribute gauge rewards

## Summary
The `_exerciseVe` function at the OptionTokenV4 wrongly assumes the paymentAmountToAddLiquidity argument is fully utilized when calling Router's `addLiquidity`. 
## Vulnerability Detail
The `_exerciseVe` function firstly calculates the payment amounts to both add liquidity and to send rewards to the gauge.
Then it transfers the sum of both payment amounts from the caller to the OptionToken contract. After that, it adds liquidity to a pair by calling the Router contract's addLiquidity function:
```solidity
(, , lpAmount) = IRouter(router).addLiquidity(
            underlyingToken,
            paymentToken,
            false,
            _amount,
            paymentAmountToAddLiquidity,
            1,
            1,
            address(this),
            block.timestamp
        );
```

Then it creates a lock for the amount of LP tokens minted.
Finally it transfers the rewards to the gauge. Notice the amount sent is the current balance of the paymentToken held by the contract:
```solidity
function _transferRewardToGauge() internal {
        uint256 paymentTokenCollectedAmount = IERC20(paymentToken).balanceOf(address(this));
...
}
```

The issue lies on the two code snippets provided. The addLiquidity function does not necessarily add the paymentAmountToAddLiquidity amount to the Pair. Actually, this argument is the amount the user desires to add.
If we reach the following snippet at the Router's `_addLiquidity` function, the amount added is smaller or equal to paymentAmountToAddLiquidity:
```solidity
function _addLiquidity(
        address tokenA,
        address tokenB,
        bool stable,
        uint amountADesired,
        uint amountBDesired,
        uint amountAMin,
        uint amountBMin
    ) internal returns (uint amountA, uint amountB) {
...
if (amountBOptimal <= amountBDesired) {
                require(amountBOptimal >= amountBMin, 'Router: INSUFFICIENT_B_AMOUNT');
               
                (amountA, amountB) = (amountADesired, amountBOptimal);
            }
...
}
```

This means the rest of the paymentAmountToAddLiquidity that had been transferred into the OptionTokenV4 contract will not be utilized to add liquidity.
It will, however, be utilized to transfer rewards to the gauge, as the function sends all the paymentTokens held by the contract at the call execution.
## Impact
Users that exercise voting escrow may send more tokens than required to pay for their lp tokens while also overpaying for gauge rewards.
## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/Router.sol#L166
https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/OptionTokenV4.sol#L593

## Tool used

Manual Review

## Recommendation
Make sure to transfer the amount of paymentAmountToAddLiquidity that was not utilized during the addLiquidity call back to the user before transferring rewards to the gauge.
The following code change should fix the issue:
```solidity
function _exerciseVe(
...
(, actualPayedAmount, lpAmount) = IRouter(router).addLiquidity(
            underlyingToken,
            paymentToken,
            false,
            _amount,
            paymentAmountToAddLiquidity,
            1,
            1,
            address(this),
            block.timestamp
        );

// added this line of code to transfer back the non-utilized amount back to the user.
_safeTransfer(paymentToken,msg.sender,paymentTokenCollectedAmount - actualPayedAmount);
        // lock underlying tokens to veFLOW
        _safeApprove(address(pair), votingEscrow, lpAmount);
        nftId = IVotingEscrow(votingEscrow).create_lock_for(
            lpAmount,
            getLockDurationForLpDiscount(_discount),//FULL_LOCK, // TODO decide
            _recipient
        );

        // notify gauge reward with payment token
        _transferRewardToGauge();
```

**Comment by WangSecurity** [comment]
Invalid based on the discussion under #299
