### ISSUE TITLE
AuditorPraise - Unsafe casting in `RewardsDistributorV2` leads to underflow of `ve_supply`

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#433]
AuditorPraise

High

# Unsafe casting in `RewardsDistributorV2` leads to underflow of `ve_supply`

## Summary
Underflow

## Vulnerability Detail
 Solidity does not revert when casting a negative number to uint. Instead, it underflows to a large
number. In the RewardDistributor contract, the ve_supply at specific time is calculated as follows:
```solidity
         ve_supply[t] = Math.max(uint(int256(pt.bias - pt.slope * dt)), 0);//@audit-issue 
```

This is supposed to return zero when the calculated balance is a negative number. However, it underflows to a large
number due to unsafe casting 

## Impact
This would lead to incorrect `ve_supply` values due to underflow. 

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L138-L139

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L263-L269
## Tool used

Manual Review

## Recommendation

instead of casting from int256 to uint256 here directly:
 `  ve_supply[t] = Math.max(uint(int256(pt.bias - pt.slope * dt)), 0);`

leave it as int256 then use a check to return 0 if it is a negative number.

Here is what i mean:
```solidity
int256 veSupply =  int256(pt.bias - pt.slope * dt);
if (veSupply < 0) return 0;
ve_supply[t] = uint256(veSupply);
```

**Comment by nevillehuang** [comment]
See comment [here](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/649#issuecomment-2283085297)
