### ISSUE TITLE
AuditorPraise - If minter mints new optionTokens to any address besides his own, he may never be able to burn them

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#437]
AuditorPraise

Medium

# If minter mints new optionTokens to any address besides his own, he may never be able to burn them

## Summary
If minter mints new optionTokens to any address besides his own, he will never be able to burn them

## Vulnerability Detail
The issue lies in the discrepancy between `OptionTokenV4.mint()` and `OptionTokenV4.burn()`

mint() mints to `to`
```solidity
function mint(address _to, uint256 _amount) external onlyMinter {
        // transfer underlying tokens from the caller
        _safeTransferFrom(underlyingToken, msg.sender, address(this), _amount);
        // mint options tokens
        _mint(_to, _amount);
    }
```

burn() burns on msg.sender but it has access control that ensures only admin can call it
```solidity
   function burn(uint256 _amount) external onlyAdmin {//@audit-issue this seems to be broken with mint() in the picture
        // transfer underlying tokens to the caller
        _safeTransfer(underlyingToken, msg.sender, _amount);
        // burn option tokensT
        _burn(msg.sender, _amount);
    }
```

The issue here is that if the admin should mint optionTokens to any address besides his own he won't be able to burn them.

## Impact
The issue here is that if the admin should mint optionTokens to any address besides his own he won't be able to burn them.
leaving as a medium because the users can still transfer their tokens to admin for him to burn it for them; BUT this isn't ideal.

The mechanism between how the mint() and burn() works is visibly faulty.
## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L519

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L532
## Tool used

Manual Review

## Recommendation

add the `to`  param to the burn() function too

**Comment by nevillehuang** [comment]
Invalid, if admin mint to another address the owner is the other user not the admin, no issue here.
