### ISSUE TITLE
eeshenggoh - Tokens are allowed to be deposited for locked NFTs for that epoch causing lesser rewards yield

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#441]
eeshenggoh

Medium

# Tokens are allowed to be deposited for locked NFTs for that epoch causing lesser rewards yield

## Summary
Users can create a lock to vote for token emission in pools. However, anyone can deposit tokens for any tokens including  against a locked NFT.

## Vulnerability Detail
Locked veNFTs are NFTs voted for pools in return for more rewards. Users should not be allowed to increase the voting power of a locked NFT by calling the `deposit_for` or `increase_amount` function because locked NFTs are not meant to be re-voted in the same epoch.  Consequently, this causes any increase in the voting balance of locked NFTs will not enhance the gauge weight, thus diminishing the influence and yield of the deposited FLOW. 

```solidity
//VotingEscrow.sol
    /// @notice Deposit `_value` tokens for `_tokenId` and add to the lock
    /// @dev Anyone (even a smart contract) can deposit for someone else, but
    ///      cannot extend thlock timetime and deposit brand-new new user
    /// @param _tokenId lock NFT
    /// @param _value Amount to add to user's lock
    function deposit_for(uint _tokenId, uint _value) external nonreentrant {
        LockedBalance memory _locked = locked[_tokenId];

        require(_value > 0); // dev: need non-zero value
        require(_locked.amount > 0, 'No existing lock found');
        require(_locked.end > block.timestamp, 'Cannot add to expired lock. Withdraw');
        _deposit_for(_tokenId, _value, 0, _locked, DepositType.DEPOSIT_FOR_TYPE);
    }

    function increase_amount(uint _tokenId, uint _value) external nonreentrant {
        assert(_isApprovedOrOwner(msg.sender, _tokenId));

        LockedBalance memory _locked = locked[_tokenId];

        assert(_value > 0); // dev: need non-zero value
        require(_locked.amount > 0, 'No existing lock found');
        require(_locked.end > block.timestamp, 'Cannot add to expired lock. Withdraw');

        _deposit_for(_tokenId, _value, 0, _locked, DepositType.INCREASE_LOCK_AMOUNT);
    }


    function voting(uint _tokenId) external {
        require(msg.sender == voter);
        voted[_tokenId] = true;
    }
```
When the user votes, the veNFTs are locked by `Voter.sol` calling `VotingEscrow.sol::voting`. Any increase in the amount will not increase the voting power in that epoch.
```solidity
//Voter.sol
    function _vote(uint _tokenId, address[] memory _poolVote, uint256[] memory _weights) internal {
        if (_usedWeight > 0) IVotingEscrow(_ve).voting(_tokenId); 
```

It wasn't stated in README.md as acceptable risk, hence the submission.
## Impact
Loss of rewards yield.

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/VotingEscrow.sol#L826
https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/VotingEscrow.sol#L871

## Tool used

Manual Review

## Recommendation
Validate if tokens are locked before allowing deposits to be called.

Duplicate of #558

**Comment by goheesheng** [comment]
Hi @nevillehuang, I quoted this comment:
> Invalid, there are no managed/locked NFT existing in this codebase not sure what this is pointing to. I believe watsons have copy the report from spearbits audit without context.
https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/558#issuecomment-2274013014

I'm not sure why it's considered a duplicate since I haven't reported on managed NFTs, as this protocol doesn't incorporate them. However, regarding the locked NFTs, they are minted when VM/WETH tokens are deposited and are specific to this protocol. My main concern in this report is that when an NFT is locked for voting power, if a user wishes to increase their voting power, it will not take effect for the current epoch after the vote has been cast. Since withdrawals aren't allowed, as indicated by this line, any additional deposits will not increase the user's reward yield because voting power remains unchanged.

Also possible to have another function to withdraw the deposited amount on a Locked NFT as a solution.
```solidity
    function withdraw(uint _tokenId) external nonreentrant {
        -- SNIP --
        require(attachments[_tokenId] == 0 && !voted[_tokenId], "attached");
        -- SNIP --
```
https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/VotingEscrow.sol#L957

**Comment by nevillehuang** [comment]
> if a user wishes to increase their voting power, it will not take effect for the current epoch after the vote has been cast.

I believe this is expected behavior that voting can only be performed once per epoch and user error analagous to most voting systems. I see no loss here. Users should consider correct amount of deposits/amount to increase before casting votes for that epoch.
