### ISSUE TITLE
AuditorPraise - Iota EVM is not compatible with block number

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#446]
AuditorPraise

Medium

# Iota EVM is not compatible with block number

## Summary
There's no enforced average block time in iota EVM  and A new EVM "block" will be created only when an ISC block is created

## Vulnerability Detail
In voting escrow there are quite  number of places where block number is used for some sort of accounting.
```solidity
u_new.blk = block.number;
```

The issue here is that IOTA EVM unlike other EVMs doesn't create blocks in the normal way..  A new EVM "block" will be created only when an ISC block is created. 

https://wiki.iota.org/isc/getting-started/compatibility/#no-enforced-block-time

## Impact
Iota EVM is not compatible with block number. A new EVM "block" will be created only when an ISC block is created. 

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/VotingEscrow.sol#L730
## Tool used

Manual Review

## Recommendation
don't use block number for accounting on IOTA EVM

**Comment by nevillehuang** [comment]
Invalid, lack details/proof and description of impact that this is an actual issue
