### ISSUE TITLE
tsueti_ - Use safeTransfer() instead of transfer()

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#45]
tsueti_

Medium

# Use safeTransfer() instead of transfer()

## Summary

The ERC20.transfer() and ERC20.transferFrom() functions return a boolean value indicating success. This parameter needs to be checked for success. Some tokens do not revert if the transfer fails but return false instead.

## Vulnerability Detail

Some tokens (like USDT) don't correctly implement the EIP20 standard and their transfer/ transferFrom function return void instead of a success boolean. Calling these functions with the correct EIP20 function signatures will always revert.

## Impact

Tokens that don't perform the transfer and return false are still counted as a correct transfer and tokens that don't correctly implement the latest EIP20 spec, like USDT, will be unusable in the protocol as they revert the transaction because of the missing return value.

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Minter.sol#L127

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L323

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/VotingEscrow.sol#L805

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/VotingEscrow.sol#L972

## Tool used

Manual Review

## Recommendation

Recommend using OpenZeppelin's SafeERC20 versions with the safeTransfer and safeTransferFrom functions that handle the return value check as well as non-standard-compliant tokens.

**Comment by nevillehuang** [comment]
Invalid, this type of behavior are only present on mainnet, in which the velocimeter has no intentions to deploy on

**Comment by cawfree** [comment]
@nevillehuang

I disagree with this outcome.

The team are only partially using a safe transfer implementation for the same source token, so clearly this issue has been taken into consideration and has not been implemented comprehensively. Issue is rooted in the token implementation and is not dependent upon the blockchain.
