### ISSUE TITLE
pashap9990 - Admin cannot burn underlyingTokens in optionTokenV4

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#458]
pashap9990

Medium

# Admin cannot burn underlyingTokens in optionTokenV4

## Summary
`OptionTokenV4::startExpire` and `OptionTokenV4::expire` will use to burn underlyingToken sent to OptionTokenV4 contract but admin cannot call them 
## Vulnerability Detail
from what the contest readme claims:
>Are there any limitations on values set by admins (or other roles) in the codebase, including restrictions on array lengths?

>No
Example deployment script with the default start settings is available in our repository in script folder.
<ins>It is used as a template for our deployments.</ins>
It has two parts - first Deployment.s.sol script needs to be run then OFlowDeployment.s.sol script.

and 
>Are there any hardcoded values that you intend to change before (some) deployments?

><ins>VotingEscrow
Name of the veNFT token
string constant public name = "veIVM";
string constant public symbol = "veIVM";

><ins>Max lock time
uint internal constant MAXTIME = 90 * 86400;
int128 internal constant iMAXTIME = 90 * 86400;</ins>
    
they just change above vars and as we can see _expiryCooldownTime has been set 0 in [OFlowDeployment.s.sol](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/script/OFlowDeployment.s.sol#L69) its mean admin cannot burn underlyingTokens    

## Impact
Admin cannot burn underlyingTokens in optionTokenV4    

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L536

## Tool used

Manual Review

## Recommendation
changing expiryCooldownTime in OFlowDeployment.s.sol to a value oposide of zero

**Comment by nevillehuang** [comment]
Invalid, the admin can simply assign the `expiryCooldownTime ` accordingly, if it is zero, it is expected to revert.

**Comment by pashap9990** [comment]
> Invalid, the admin can simply assign the `expiryCooldownTime ` accordingly, if it is zero, it is expected to revert.

I just had submited this issue for be more familair with Sherlock's rule ,u mean admin can update expiryCooldownTime? @nevillehuang
