### ISSUE TITLE
bareli - old router approval should be approved to zero.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#465]
bareli

Medium

# old router approval should be approved to zero.

## Summary
As we are changing router in setrouter  and earlier we have approve router as   _safeApprove(underlyingToken, router, _amount);
    and     _safeApprove(paymentToken, router, paymentAmountToAddLiquidity);  
we should approve this to zero before changing the router.
## Vulnerability Detail
 function _exerciseVe(
        uint256 _amount,
        uint256 _maxPaymentAmount,
        uint256 _discount,
        address _recipient
    ) internal returns (uint256 paymentAmount, uint256 nftId,uint256 lpAmount) {
        if (isPaused) revert OptionToken_Paused();
        if (isExerciseVePaused) revert OptionToken_Paused();

        if (_discount > minLPDiscount || _discount < maxLPDiscount)
            revert OptionToken_InvalidDiscount();
            
        // burn callers tokens
        _burn(msg.sender, _amount);
        (uint256 paymentAmount,uint256 paymentAmountToAddLiquidity) =  getPaymentTokenAmountForExerciseLp(_amount,_discount); // TODO decide if we want to have the curve or just always maxlock
        if (paymentAmount > _maxPaymentAmount)
            revert OptionToken_SlippageTooHigh();
          
        // Take team fee
        uint256 paymentGaugeRewardAmount = _discount == 0 ? 0 : _takeFees(
            paymentToken,
            paymentAmount
        );
        _safeTransferFrom(
            paymentToken,
            msg.sender,
            address(this),
            paymentGaugeRewardAmount + paymentAmountToAddLiquidity
        );

        // Create Lp for users
   @>     _safeApprove(underlyingToken, router, _amount);
     @>   _safeApprove(paymentToken, router, paymentAmountToAddLiquidity);
        (, , lpAmount) = IRouter(router).addLiquidity(
            underlyingToken,
            paymentToken,
            false,
            _amount,
            paymentAmountToAddLiquidity,
            1,
            1,
            address(this),
            block.timestamp
        );

        // lock underlying tokens to veFLOW
        _safeApprove(address(pair), votingEscrow, lpAmount);
        nftId = IVotingEscrow(votingEscrow).create_lock_for(
            lpAmount,
            getLockDurationForLpDiscount(_discount),//FULL_LOCK, // TODO decide
            _recipient
        );

        // notify gauge reward with payment token
        _transferRewardToGauge();

        emit ExerciseVe(msg.sender, _recipient, _amount, paymentAmount, nftId);
    }

    function _exerciseLp(
        uint256 _amount,   // the oTOKEN amount the user wants to redeem with
        uint256 _maxPaymentAmount, // the 
        address _recipient,
        uint256 _discount
    ) internal returns (uint256 paymentAmount, uint256 lpAmount) {
        if (isPaused) revert OptionToken_Paused();
        if (isExerciseLpPaused) revert OptionToken_Paused();

        if (_discount > minLPDiscount || _discount < maxLPDiscount)
            revert OptionToken_InvalidDiscount();

        // burn callers tokens
        _burn(msg.sender, _amount);
        (uint256 paymentAmount,uint256 paymentAmountToAddLiquidity) =  getPaymentTokenAmountForExerciseLp(_amount,_discount);
        if (paymentAmount > _maxPaymentAmount)
            revert OptionToken_SlippageTooHigh();
          
        // Take team fee
        uint256 paymentGaugeRewardAmount = _discount == 0 ? 0 : _takeFees(
            paymentToken,
            paymentAmount
        );
        _safeTransferFrom(
            paymentToken,
            msg.sender,
            address(this),
            paymentGaugeRewardAmount + paymentAmountToAddLiquidity
        );

        // Create Lp for users
   @>     _safeApprove(underlyingToken, router, _amount);
    @>    _safeApprove(paymentToken, router, paymentAmountToAddLiquidity);

   function setRouter(address _router) external onlyAdmin {
    @>    router = _router;
        emit SetRouter(_router);
    }
## Impact
old router can cause a loss  of underlyingToken and paymentToken.
## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L446
## Tool used

Manual Review

## Recommendation
 function setRouter(address _router) external onlyAdmin {
      
         @>  _safeApprove(underlyingToken, router,0);
    @>    _safeApprove(paymentToken, router, 0);
              router = _router;

        emit SetRouter(_router);

**Comment by nevillehuang** [comment]
Invalid, this is not required given the router can just simply be deprecated and not be used by the user
