### ISSUE TITLE
bareli - wrong assign of teamRate in "constructor"

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#466]
bareli

Medium

# wrong assign of teamRate in "constructor"

## Summary
in the constructor in the comment its written that teamRate is  30 bps but its assigned to 50.
## Vulnerability Detail
 constructor(
        address __voter, // the voting & distribution system
        address __ve, // the ve(3,3) system that will be locked into
        address __rewards_distributor // the distribution system that ensures users aren't diluted
    ) {
        initializer = msg.sender;
        team = msg.sender;
        teamEmissions = msg.sender;
   @>     teamRate = 50; // 30 bps = 3%
## Impact
wrong implement of update_period()
## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Minter.sol#L49
## Tool used

Manual Review

## Recommendation
    teamRate = 30; // 30 bps = 3%

**Comment by nevillehuang** [comment]
Invalid, documentation error
