### ISSUE TITLE
StraawHaat - Incorrect calculation in several places in `RewardsDistributorV2.sol` because unsafe casting

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#476]
StraawHaat

High

# Incorrect calculation in several places in `RewardsDistributorV2.sol` because unsafe casting

## Summary

**Note** the same issue is also applicable to two other functions: `_checkpoint_total_supply()` and `_claim`, but I will give example with `ve_for_at()`.

Incorrect voting calculation in `ve_for_at()` because unsafe cast:

```solidity
(uint(int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts))))), 0)
```

When we cast a negative `int256` to a `uint`, it does not revert but instead performs a bitwise cast, resulting in an underflow. This means that the negative number will wrap around to a large positive number.
## Vulnerability Detail

`ve_for_at()` function calculate the `ve` (Voting Escrow) balance of a specific NFT token at a given timestamp. This balance represents the voting power associated with the token:

```solidity
    function ve_for_at(uint _tokenId, uint _timestamp) external view returns (uint) {
        address ve = voting_escrow;
        uint max_user_epoch = IVotingEscrow(ve).user_point_epoch(_tokenId);
        uint epoch = _find_timestamp_user_epoch(ve, _tokenId, _timestamp, max_user_epoch);
        IVotingEscrow.Point memory pt = IVotingEscrow(ve).user_point_history(_tokenId, epoch); 
        return Math.max(uint(int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts))))), 0);
    }
```

The problem here is that we have incorrect voting calculation because the return value may be negative, and then it is cast to `uint`:

```solidity
uint(int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts)))))
```

When we cast a negative `int256` to a `uint`, it does not revert but instead performs a bitwise cast, resulting in an underflow. This means that the negative number will wrap around to a large positive number.

When `pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts` is negative value, the resulting voting power should be 0.

**Note** the same issue is also applicable to two other functions: `_checkpoint_total_supply()` and `_claim`.
## Impact

Incorrect voting calculation. When the calculation returns a negative number, the result should be 0. Instead, it will return a positive number because of the overflow. This would lead also to incorrect reward distribution.
Also `_checkpoint_total_supply()` will return wrong supply, and `_claim()` will return wrong balance.
## Code Snippet

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L139
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L158
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L208

## Tool used

Manual Review

## Recommendation

Return zero when the number is negative

**Comment by nevillehuang** [comment]
See comment [here](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/649#issuecomment-2283085297)
