### ISSUE TITLE
StraawHaat - It is possible that `setHasGauge` fail and thus the pool will has a wrong value of `hasGauge`

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#487]
StraawHaat

Medium

# It is possible that `setHasGauge` fail and thus the pool will has a wrong value of `hasGauge`

## Summary

It is possible that `setHasGauge` fail, and thus, the pool will have a wrong value of `hasGauge`.
This is because when calling the `setHasGauge` function, it is possible to fail, and the pool itself will be left with a wrong value whether there is a gauge or not.

## Vulnerability Detail

The `pauseGauge()`, `restartGauge()`, and `killGaugeTotally()` functions are used by the admin to set the given Gauge state. 

All three functions call `setHasGauge()` in `Pair.sol`. Let's give an example with `restartGauge()`:

```solidity
    function restartGauge(address _gauge) external {
        if (msg.sender != emergencyCouncil) {
            require(
                IGaugePlugin(gaugePlugin).checkGaugeRestartAllowance(msg.sender, _gauge)
            , "Restart gauge not allowed");
        }
        require(!isAlive[_gauge], "gauge already alive");
        isAlive[_gauge] = true;
        address _pair = IGauge(_gauge).stake(); // TODO: add test cases
        try IPair(_pair).setHasGauge(true) {} catch {}
        emit GaugeRestarted(_gauge);
    }
```

`emergencyCouncil` decides to restart a Gauge. The function at the end calls:
```solidity
try IPair(_pair).setHasGauge(true) {} catch {}
```
Because it is in `try/catch` block we assume the scenario that it will fail.

`setHasGauge()` is called and fails to change the activate on the given Gauge:

```solidity
    function setHasGauge(bool value) external {
        require(msg.sender == voter, 'Only voter can set has gauge');
        hasGauge = value;
        emit HasGaugeSet(value);
    }
```

Since we have nothing in `catch` to catch the error, this means that the `restartGauge()` function will assume that there is no error.

This means that the pool remains without an associated gauge. And also means that `swap()` will not take any fees:

```solidity
        if (hasGauge){
            if (amount0In != 0) _sendTokenFees(token0, fee0);
            if (amount1In != 0) _sendTokenFees(token1, fee1);
        } 
```
## Impact

The impact varies depending on the scenario. If the admin wants to activate a gauge, however, the value remains at `false`, which means no fees will be collected. If the admin wants to remove a Gauge and fails, this means that a non-existent Gauge will take charges.

## Code Snippet

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Voter.sol#L380-L429
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Pair.sol#L128-L132
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Pair.sol#L321-L324

## Tool used

Manual Review

## Recommendation

Best to remove the `try/catch` block to allow the function to revert if it fails.

**Comment by nevillehuang** [comment]
Invalid, if admin (`emergencyCouncil`) executes restart appropriately, this will never revert. Also if there really is no gauge, then yes fees should not be sent, if not it could be lost
