### ISSUE TITLE
StraawHaat - The `swap()` function will often fail, or it will not check the balance correctly via `_k()`, because it does not check the correct `_balance0` and `_balance1`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#488]
StraawHaat

Medium

# The `swap()` function will often fail, or it will not check the balance correctly via `_k()`, because it does not check the correct `_balance0` and `_balance1`

## Summary

The `swap()` function will often fail, or it will not check the balance correctly via `_k()`, because it does not check the correct `_balance0` and `_balance1`

The function first checks the pool maintains its balance during swaps, and, after this takes the real balance:

```solidity
        require(_k(_balance0, _balance1) >= _k(_reserve0, _reserve1), 'K'); // Pair: K
        }
        _balance0 = IERC20(token0).balanceOf(address(this));
        _balance1 = IERC20(token1).balanceOf(address(this));
```
## Vulnerability Detail

In `Pair.sol`, the `swap()` function swaps tokens within the liquidity pool. 

We need to pay attention to the second part of the function:
```solidity
        if (hasGauge){
            if (amount0In != 0) _sendTokenFees(token0, fee0);
            if (amount1In != 0) _sendTokenFees(token1, fee1);
        }

        if (amount0In != 0) _balance0 = _balance0 - fee0;
        if (amount1In != 0) _balance1 = _balance1 - fee1;
        // The curve, either x3y+y3x for stable pools, or x*y for volatile pools
        require(_k(_balance0, _balance1) >= _k(_reserve0, _reserve1), 'K'); // Pair: K
        }
        _balance0 = IERC20(token0).balanceOf(address(this));
        _balance1 = IERC20(token1).balanceOf(address(this));
        _update(_balance0, _balance1, _reserve0, _reserve1);
```

First, we check if the pool has an associated gauge. We then reduce the fees from `_balance0`  and `_balance1`. 

Then we check the new invariant `_k(_balance0, _balance1)` after the swap is greater than or equal to the invariant `_k(_reserve0, _reserve1)` before the swap.

And here is the problem if there is no Gauge, it will unnecessarily subtract fees and then check with wrong `_balance0`  and `_balance1` values. 
And only then the real `_balance0`  and `_balance1` will be taken.

The invariant check would be performed on these reduced balances, which might not reflect the actual state of the contract.

Require statement should be after:
```solidity
        _balance0 = IERC20(token0).balanceOf(address(this));
        _balance1 = IERC20(token1).balanceOf(address(this));
```

The curve, either `x3y+y3x` for stable pools, or `x*y` for volatile pools, will be wrong.
## Impact

The `_k` invariant check ensures the pool remains balanced, allowing valid swaps to proceed and preventing invalid ones. A valid swap operation may not work due to an incorrect check. The other scenario is not to meet the curve formula.
## Code Snippet

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Pair.sol#L321-L333
## Tool used

Manual Review

## Recommendation

You need to move `require(_k)` after `_balance0`  and `_balance1` :

```solidity
        require(_k(_balance0, _balance1) >= _k(_reserve0, _reserve1), 'K'); // Pair: K
        
        _balance0 = IERC20(token0).balanceOf(address(this));
        _balance1 = IERC20(token1).balanceOf(address(this));
```

**Comment by nevillehuang** [comment]
Invalid, duplicate of #557, also see identical implementation in [velodrome](https://optimistic.etherscan.io/address/0x25cbddb98b35ab1ff77413456b31ec81a6b6b746#code)

**Comment by StraawHaat** [comment]
Escalate

This issue is not a duplicate of #557, and it's a valid issue. 

My issue is about checking `_balance0` and `_balance1` first and then taking their value, which is completely wrong and will lead to a wrong curve check.

You very well provided a link to Velodrome to see how it is properly implemented there:

Velocimeter **Incorrect:**
```solidity
// The curve, either x3y+y3x for stable pools, or x*y for volatile pools
require(_k(_balance0, _balance1) >= _k(_reserve0, _reserve1), 'K'); // Pair: K
}   
_balance0 = IERC20(token0).balanceOf(address(this)); 
_balance1 = IERC20(token1).balanceOf(address(this));
```

Velodrome **Correct:**
```solidity
_balance0 = IERC20(_token0).balanceOf(address(this));
_balance1 = IERC20(_token1).balanceOf(address(this));
// The curve, either x3y+y3x for stable pools, or x*y for volatile pools
require(_k(_balance0, _balance1) >= _k(_reserve0, _reserve1), 'K'); // Pair: K
```

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This issue is not a duplicate of #557, and it's a valid issue. 
> 
> My issue is about checking `_balance0` and `_balance1` first and then taking their value, which is completely wrong and will lead to a wrong curve check.
> 
> You very well provided a link to Velodrome to see how it is properly implemented there:
> 
> Velocimeter **Incorrect:**
> ```solidity
> // The curve, either x3y+y3x for stable pools, or x*y for volatile pools
> require(_k(_balance0, _balance1) >= _k(_reserve0, _reserve1), 'K'); // Pair: K
> }   
> _balance0 = IERC20(token0).balanceOf(address(this)); 
> _balance1 = IERC20(token1).balanceOf(address(this));
> ```
> 
> Velodrome **Correct:**
> ```solidity
> _balance0 = IERC20(_token0).balanceOf(address(this));
> _balance1 = IERC20(_token1).balanceOf(address(this));
> // The curve, either x3y+y3x for stable pools, or x*y for volatile pools
> require(_k(_balance0, _balance1) >= _k(_reserve0, _reserve1), 'K'); // Pair: K
> ```

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
This issue is invalid, I believe the watson was not careful enough when analyzing the code logic for `k` checks, so I would have to be more detailed to explain to him.

Velodrome Implementation
In velodrome implementation, `_update0()` and `update1()` will pull fees out of the pair contract. Then, `_balance0` and `_balance1` will be reinitiated with current balance of pair contract, meaning fees are not part of the k invariant check. This was even noted in the comments

`since we removed tokens, we need to reconfirm balances, can also simply use previous balance - amountIn/ 10000, but doing balanceOf again as safety check`

```solidity
	if (amount0In > 0) _update0(amount0In * PairFactory(factory).getFee(stable) / 10000); // accrue fees for token0 and move them out of pool
	if (amount1In > 0) _update1(amount1In * PairFactory(factory).getFee(stable) / 10000); // accrue fees for token1 and move them out of pool
	_balance0 = IERC20(_token0).balanceOf(address(this)); // since we removed tokens, we need to reconfirm balances, can also simply use previous balance - amountIn/ 10000, but doing balanceOf again as safety check
	_balance1 = IERC20(_token1).balanceOf(address(this));
	// The curve, either x3y+y3x for stable pools, or x*y for volatile pools
	require(_k(_balance0, _balance1) >= _k(_reserve0, _reserve1), 'K'); // Pair: K
	}
```

Velocimeter
Referring to the previous comment, this is exactly what velocimeter did
`since we removed tokens, we need to reconfirm balances, can also simply use previous balance - amountIn/ 10000, but doing balanceOf again as safety check`

Here, they decrement the fees from the `_balance0` and `_balance1` and invoked the k invariant check first, so it has an identical meaning to velodrome's implentation, no issue here i.e. fees are not part of the invariant check.

```soldiity
	if (amount0In != 0) _balance0 = _balance0 - fee0;
	if (amount1In != 0) _balance1 = _balance1 - fee1;
	// The curve, either x3y+y3x for stable pools, or x*y for volatile pools
	require(_k(_balance0, _balance1) >= _k(_reserve0, _reserve1), 'K'); // Pair: K
	}
```

**Comment by StraawHaat** [comment]
But isn't the logic in the two contracts the same?

In both code snippets, you have shown, the logic is the same. The fees are removed. It is even written as a comment:

**Velodorom** accrues fees and removes them. After this, synchronize the balance and do a check:
```solidity
        if (amount0In > 0) _update0(amount0In * PairFactory(factory).getFee(stable) / 10000); // accrue fees for token0 and move them out of pool
        if (amount1In > 0) _update1(amount1In * PairFactory(factory).getFee(stable) / 10000); // accrue fees for token1 and move them out of pool
        _balance0 = IERC20(_token0).balanceOf(address(this)); // since we removed tokens, we need to reconfirm balances, can also simply use previous balance - amountIn/ 10000, but doing balanceOf again as safety check
        _balance1 = IERC20(_token1).balanceOf(address(this));
        // The curve, either x3y+y3x for stable pools, or x*y for volatile pools
        require(_k(_balance0, _balance1) >= _k(_reserve0, _reserve1), 'K'); // Pair: K
```

**Velodorom** accrues fees and removes them. First, do the check, after this synchronize the balance: 
```solidity
        if (amount0In != 0) _balance0 = _balance0 - fee0;
        if (amount1In != 0) _balance1 = _balance1 - fee1;
        // The curve, either x3y+y3x for stable pools, or x*y for volatile pools
        require(_k(_balance0, _balance1) >= _k(_reserve0, _reserve1), 'K'); // Pair: K
        }
        
        _balance0 = IERC20(token0).balanceOf(address(this)); 
        _balance1 = IERC20(token1).balanceOf(address(this));
```

@dawiddrzala Can you tell me what your opinion is?

**Comment by nevillehuang** [comment]
Fees does not belong to the pool since it is transferred out, so there is no issue here, not sure what additional clarification is required.

**Comment by dawiddrzala** [comment]
when we do not have the gauge the fee still applies, they are just auto compounded to the pool in our scenario like standard uniswap v2, ( that why the k check needs to pass without the fee, ( user pays the fee),  so the issues is not valid

**Comment by cvetanovv** [comment]
Taking into consideration the Lead Judge's and the sponsor's comments, we understand that the `k` check should pass without the fee. That's why we don't have any issues here.

Planning to reject the escalation and leave the issue as is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [StraawHaat](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/488/#issuecomment-2283503878): rejected
