### ISSUE TITLE
krkba - IERC20(token).approve revert if the underlying ERC20 token approve does not return boolean

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#49]
krkba

Medium

# IERC20(token).approve revert if the underlying ERC20 token approve does not return boolean

krkbaa
## Summary
IERC20(token).approve revert if the underlying ERC20 token approve does not return boolean
## Vulnerability Detail
in OptionTokenV4.sol contract _safeApprove function:
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L780-L791

when approving the token, the safeApprove is not used for non-standard token such as USDT,
calling approve will revert because the solmate ERC20 enforce the underlying token return a boolean
https://github.com/transmissions11/solmate/blob/e0e9ff05d8aa5c7c48465511f85a6efdf5d5c30d/src/tokens/ERC20.sol#L68-L74

while the token such as USDT does not return boolean

https://etherscan.io/address/0xdac17f958d2ee523a2206206994597c13d831ec7#code#L126
## Impact
USDT or other ERC20 token that does not return boolean for approve are not supported.
## Tool used

Manual Review

## Recommendation
Use safeApprove instead of approve

**Comment by nevillehuang** [comment]
Invalid, such weird token behavior only occurs on mainnet, in which velocimeter has no intentions of deploying to. See [here](https://explorer.evm.iota.org/token/0xC1B8045A6ef2934Cf0f78B0dbD489969Fa9Be7E4?tab=contract)
