### ISSUE TITLE
Hajime - Checkpoints will not update block.number in point because of a Rounding issue

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#497]
Hajime

Medium

# Checkpoints will not update block.number in point because of a Rounding issue

## Summary
Voting Escrow Checkpoints won't update block number in point because of a Rounding issue, currently the block time in Ethereum is around 12 seconds, There is an attempt to calculate block slope by the difference of the block number multiplied by a `MULTIPLIER` and then divided by the difference in block.timestamp.

There is an issue because of the precision of the division.

## Vulnerability Detail
In _checkpoint of VotingEscrow there is a line

`block_slope = (MULTIPLIER * (block.number - last_point.blk)) / (block.timestamp - last_point.ts);`

Here blockSlope will always be zero as for each block.number the difference in block.timestamp is around ~ 12 seconds. The MULTIPLIER : 1 is too low to cover that and as a result it becomes zero as the numerator is lesser than the denominator

`last_point.blk = initialLastPoint.blk + (block_slope * (_time - initialLastPoint.ts)) / MULTIPLIER;` The result will be stagnation and will never be up to date.

## Impact
The Point objects used in _checkpoint never have their block value updated. This will affect any off-calculation/computation that relies on the block number for points to make a transaction
## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/VotingEscrow.sol#L675
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/VotingEscrow.sol#L645
## Tool used

Manual Review

## Recommendation
Increase MULTIPLIER to a much higher value

**Comment by nevillehuang** [comment]
Invalid, the `MULTIPLIER` is 1e18 as seen [here](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/VotingEscrow.sol#L565), not 1, so round down is not possible/extremely unlikely.
