### ISSUE TITLE
kevinkien - ERC20 Flow Contract - Underflow Vulnerability in _burn Function

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#5]
kevinkien

Medium

# ERC20 Flow Contract - Underflow Vulnerability in _burn Function

## Summary
The _burn function in the `Flow.sol` contract lacks input validation, potentially leading to an underflow vulnerability. This can enable malicious actors to create tokens out of thin air and disrupt the contract's intended logic.

## Vulnerability Detail
The `_burn` function does not verify if the `amount` of tokens being burned exceeds the user's actual balance (`balanceOf[from]`). In the absence of this check, an underflow can occur when a user tries to burn more tokens than they possess. This results in the user's balance wrapping around to a very large positive number instead of becoming negative.

## Impact
Underflow errors can break calculations and logic

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Flow.sol#L48
```solidity
function _burn(address from, uint256 amount) internal {
    balanceOf[from] -= amount; // No underflow check
}
```

## Tool used

Manual Review

## Recommendation
add a require statement at the beginning of the _burn function to enforce that the burn amount does not exceed the user's balance:

```solidity
function _burn(address from, uint256 amount) internal {
+    require(balanceOf[from] >= amount, "ERC20: burn amount exceeds balance");
     balanceOf[from] -= amount;
}
```

**Comment by nevillehuang** [comment]
Invalid, an explicit check is not required, if there is insufficient amount to burn, underflow is correct
