### ISSUE TITLE
0xNazgul - Unsafe casting in `RewardsDistributorV2` leads to underflow of `ve_For_At`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#503]
0xNazgul

Medium

# Unsafe casting in `RewardsDistributorV2` leads to underflow of `ve_For_At`

## Summary

During the calculations of the function `ve_For_At` there is a casting from `int` to `uint` that could lead to overflow.

## Vulnerability Detail

Solidity does not revert when casting a negative number to uint. Instead, it underflows to a large number. In the `RewardDistributorV2` contract, the balance of a token at specific time is calculated as follows:
```solidity
        IVotingEscrow.Point memory pt = IVotingEscrow(ve).user_point_history(_tokenId, epoch);
        return Math.max(uint(int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts))))), 0);
```
This supposes to return zero when the calculated balance is a negative number. However, it underflows to a large number.

## Impact

This would lead to incorrect reward distribution if third-party protocols depend on this function, or when further updates make use of this codebase.

## Code Snippet

[RewardsDistributorV2.sol#L134](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L134)

This is also true for the out of scope [RewardsDistributor.sol#L135](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributor.sol#L135).

## Tool used

Manual Review

## Recommendation
Recommend following other parts of the codebase and returning zero for a negative number.

**Comment by nevillehuang** [comment]
See comment [here](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/649#issuecomment-2283085297)
