### ISSUE TITLE
cryptic - Exercise options pause mechanism lacks unpause mechanism

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#516]
cryptic

Medium

# Exercise options pause mechanism lacks unpause mechanism

## Summary
The `OptionTokenV4` contract constructor takes in the following parameters: `isExerciseLpPaused`, `isExerciseVePaused`, `isExercisePaused`.

The purpose of this is to pause individual `exercise` options, whereas the `isPaused` parameter pauses all the exercise options together.

Although there is a possibility to trigger pause/unpause for `isPaused`, none of the individual pause parameters have the ability to unpause.

If any of `isExerciseLpPaused`, `isExerciseVePaused`, `isExercisePaused` are triggered, it will be permanently lock the respective `exercise option` function.

## Vulnerability Detail

`OptionTokenV4` constructor allows the following variables to be set:

[OptionTokenV4.sol#L232-L234](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L232-L234)
```javascript
    isExerciseLpPaused = _isExerciseLpPaused;
    isExerciseVePaused = _isExerciseVePaused;
    isExercisePaused = _isExercisePaused;
```

Each variable will pause the respective exercise option function: `exerciseLP`, `exerciseVe` , `exercise`.

For example, let's take a look at `exercise`:

[OptionTokenV4.sol#L569-L575](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L569-L575)
```javascript
    function _exercise(
        uint256 _amount,
        uint256 _maxPaymentAmount,
        address _recipient
    ) internal returns (uint256 paymentAmount) {
        if (isPaused) revert OptionToken_Paused();
@>      if (isExercisePaused) revert OptionToken_Paused();
```

As mentioned, `isPaused` pauses all the `exercise` functions, but the contract also has the ability to pause individual exercise functions.

The problem is that there is no function that allows an admin to unpause the individual pause variables, causing the functions to permanently locked.

## Impact

Excercise options may be permanently paused, causing DoS to core functionalities of the `OptionTokenV4` contract.

## Code Snippet

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L232-L234

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/OptionTokenV4.sol#L569-L575

## Tool used

Manual Review

## Recommendation

Add unpause mechanisms to each exercise option pause variable

**Comment by nevillehuang** [comment]
Invalid `isExerciseLpPaused` and `isExerciseVePaused` will permanently block exeriscing of options. If the admin deploying contract wish to retain flexibility to unpause, he should set `isExercisePaused = true` and while setting `isExerciseLpPaused/isExerciseVePaused`  to false
