### ISSUE TITLE
Minato7namikazi - supply tracking issues in the `_deposit_for` and `_remove_from` functions.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#548]
Minato7namikazi

Medium

# supply tracking issues in the `_deposit_for` and `_remove_from` functions.

## Vulnerability Detail

 in the `_deposit_for` and `_remove_from` functions. These functions are responsible for updating the total supply, but they don't handle the case of extending lock time correctly.

the resposible part in the `_deposit_for` function:

```solidity
supply = supply_before + _value;
```

And in the `_remove_from` function:

```solidity
supply = supply_before - _value;
```

The issue is that these functions always update the supply based on the `_value` parameter, even when the operation is just extending the lock time (i.e., `_value` is 0). This can lead to incorrect supply tracking in the following scenarios:

1. When increasing the lock time without adding more tokens (`increase_unlock_time` function), the supply shouldn't change, but the current implementation might change it if `_value` is non-zero.

2. When creating a new lock or adding to an existing lock, the supply increase should be based on the actual new tokens being locked, not just the `_value` parameter.

3. When withdrawing tokens, the supply decrease should be based on the actual tokens being withdrawn, not just the `_value` parameter.

## Code Snippet

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/VotingEscrow.sol#L777

## Tool used

Manual Review

**Comment by nevillehuang** [comment]
Invalid, the statements are all wrong. `_value` is the desired token amount to deposit/withdraw, there is no issue here. If you input 0 value, then supply should not be increased, that is correct.
