### ISSUE TITLE
Hajime - Lack of revert statement in `Voter.poke` results in freezing of yield for an entire epoch

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#552]
Hajime

Medium

# Lack of revert statement in `Voter.poke` results in freezing of yield for an entire epoch

## Summary
There is no revert statement in Voter.sol::poke for first time callers resulting in loss of yield for the epoch
## Vulnerability Detail
The Voter.sol::poke function doesn't revert when _poolCnt = 0 (_poolVote.length = 0), i.e for first time voters.
` uint _poolCnt = _poolVote.length; ` should revert if length = 0.
So, if a first time voter calls `poke` then he will be marked as voted without even voting for anyone because of empty poolVote[_tokenId] array. This will prevent him from getting any yield. The situation becomes even worse because he can't even call vote function also because of onlyNewEpoch modifier.
```solidity
   function vote(uint tokenId, address[] calldata _poolVote, uint256[] calldata _weights) external onlyNewEpoch
```
User will only be able to vote in the next epoch and all his yield will be lost permanently. This can easily be prevented with a revert statement.

## Impact
User will lose his yield for the entire epoch.
## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Voter.sol#L234-L247
## Tool used

Manual Review

## Recommendation
Modify the function add
```solidity
require(_poolCnt > 0, "first vote" );
```

**Comment by nevillehuang** [comment]
Invalid, if `poolCnt == 0`, the for loop will not be entered and the whole logic for voting assignments will not execute at all per [here](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Voter.sol#L234-L285), there is no issue here. Additionally, this would consitute user input error not valid based on sherlock rules
