### ISSUE TITLE
Minato7namikazi - fees are deducted from (`_balance0` and `_balance1`) regardless of whether `hasGauge` is true or false.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#557]
Minato7namikazi

Medium

# fees are deducted from (`_balance0` and `_balance1`) regardless of whether `hasGauge` is true or false.

## Vulnerability Detail

in the `swap` function. The issue is related to the fee calculation and deduction:

```solidity
uint fee0 = amount0In * IPairFactory(factory).getFee(address(this)) / 10000;
uint fee1 = amount1In * IPairFactory(factory).getFee(address(this)) / 10000;

if (hasGauge){
    if (amount0In != 0) _sendTokenFees(token0, fee0);
    if (amount1In != 0) _sendTokenFees(token1, fee1);
} 

if (amount0In != 0) _balance0 = _balance0 - fee0;
if (amount1In != 0) _balance1 = _balance1 - fee1;
```

The bug is that the fees are deducted from the balances (`_balance0` and `_balance1`) regardless of whether `hasGauge` is true or false. This means that even when `hasGauge` is false and fees are not sent to the external bribe contract, the fees are still subtracted from the balances.

This can lead to a discrepancy between the actual token balances in the contract and the recorded balances used for calculations, potentially causing issues with liquidity calculations and future swaps.

To fix this, the fee deduction should only occur when `hasGauge` is true.

## Code Snippet

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Pair.sol#L318

## Tool used

Manual Review

**Comment by nevillehuang** [comment]
Invalid, intended for the k invariant check [here](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Pair.sol#L329), subsequently will be reassigned [here](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Pair.sol#L332-L333). Fees are not part of the reserves. also see identical implementation in [velodrome](https://optimistic.etherscan.io/address/0x25cbddb98b35ab1ff77413456b31ec81a6b6b746#code)
