### ISSUE TITLE
Hajime - `_bribes` and `_tokens` length are not checked to be equal

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#562]
Hajime

Medium

# `_bribes` and `_tokens` length are not checked to be equal

## Summary
In `Voter.claimBribes, _bribes` and `_tokens` length are not checked to be equal.
## Vulnerability Detail
No array lengths check in `Voter.claimBribes`
```solidity   
 function claimBribes(address[] memory _bribes, address[][] memory _tokens, uint _tokenId) external {
        require(IVotingEscrow(_ve).isApprovedOrOwner(msg.sender, _tokenId));
        for (uint i = 0; i < _bribes.length; i++) {
            IBribe(_bribes[i]).getRewardForOwner(_tokenId, _tokens[i]);
        }
    }
```
This can create problem in a scenario where `_bribes` length is less than `_tokens` length as the user will lose on the funds on the bribe which is not set in the array. Such checks are essential in order to validate that valid transactions are going through and there is no discrepancy between bribes and tokens.
## Impact
Lack of this check can result in user putting wrong lengths of bribes and tokens. This can create problem in a scenerio where `_bribes` length is less than _tokens length as the user will lose on the funds on the bribe which is not set in the array.
## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Voter.sol#L542-L547
## Tool used

Manual Review

## Recommendation
add
```require(_bribes.length == _tokens.length, "token and bribes are not equal");```

**Comment by nevillehuang** [comment]
Invalid, user input error, they can simply claim again for specific tokens from bribes, no rewards will be lost.
