### ISSUE TITLE
Chinmay - Unsafe casting of int to uint in RewardsDistributor

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#594]
Chinmay

Medium

# Unsafe casting of int to uint in RewardsDistributor

## Summary
RewardsDistributorV2 contract has instances of converting an integer value to uint without considering that the integer could be a negative number.  

## Vulnerability Detail
For example see this checkpoint_total_supply function :
```solidity

    function _checkpoint_total_supply() internal {
        address ve = voting_escrow;
        uint t = time_cursor;

   ...some code  
                ve_supply[t] = Math.max(uint(int256(pt.bias - pt.slope * dt)), 0); // 
            }
   ...some code
    }
```
We want the ve_supply to be recorded as a positive number, or zero. But the problem here is that the current logic defeats the purpose of Math.max. Since the int256 value is first being converted to uint256, this will never evaluate zero. If the result of ```pt.bias - pt.slope * dt``` is negative, then the conversion to uint will cause underflow and yield a very large positive number. 

The danger of doing a conversion first is that (bias - slope * dt) which are all signed integers has a possibility of being a negative result (i.e. less than 0). But because it is converted to a uint256 first, it will result in a very large uint256 (underflow).

```solidity
Math.max(uint128(-1), 0) // 115792089237316195423570985008687907853269984665640564039457584007913129639935
```

## Impact
Possible underflow due to converting a negative number directly to uint resulting in a large positive number. This will result in the ve_supply getting stored as a very high incorrect value which is meant to be used further when claiming rewards, thus inaccurate rewards will be distributed. 

There are more instances of this issue in RewardsDistributorV2.sol.

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L158

## Tool used

Manual Review

## Recommendation
Do max comparison first then convert to uint256:

```solidity
ve_supply[t] = uint256(int256(Math.maxInt((pt.bias - pt.slope * dt), 0)));
```

**Comment by nevillehuang** [comment]
See comment [here](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/649#issuecomment-2283085297)
