### ISSUE TITLE
0xShoonya - Potential underflow in `RewardsDistributorV2.sol` due to Unsafe Casting

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#617]
0xShoonya

Medium

# Potential underflow in `RewardsDistributorV2.sol` due to Unsafe Casting

## Summary
In the  `RewardsDistributorV2.sol`, the calculation of a token's balance at a specific time (`veForAt`) involves unsafe casting from `int256` to `uint256`. This can result in severe underflow when the calculated balance is negative, leading to incorrectly large balances instead of the intended zero value.

## Vulnerability Detail
[veForAt](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L134-L140) function in  `RewardsDistributorV2.sol` is implemented as follows: 
```js
    function ve_for_at(uint _tokenId, uint _timestamp) external view returns (uint) {
        address ve = voting_escrow;
        uint max_user_epoch = IVotingEscrow(ve).user_point_epoch(_tokenId);
        uint epoch = _find_timestamp_user_epoch(ve, _tokenId, _timestamp, max_user_epoch);
        IVotingEscrow.Point memory pt = IVotingEscrow(ve).user_point_history(_tokenId, epoch);
@>      return Math.max(uint(int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts))))), 0);
    }
```
The issue arises from the following sequence of operations:

1. The balance is calculated as `pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts)))`, which can result in a negative value.
2. This potentially negative value is cast to `uint256`.
3. In `Solidity`, casting a negative `int256` to `uint256` does not result in 0 or throw an error. Instead, it `underflows`, resulting in a very large positive number.
4. The `Math.max()` function then compares this large number with 0, always returning the large underflowed number.

This vulnerability bypasses the intended logic of returning 0 for negative balances, instead returning extremely large, incorrect balances.

Other instances of this issue: [RewardsDistributorV2.sol#L158](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L158), [RewardsDistributorV2.sol#L208](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L208), [RewardsDistributorV2.sol#L265](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L265)

## Impact
This would lead to incorrect reward distribution if third-party protocols depend on this function, or when further
updates make use of this codebase

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L134-L140
https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L158
https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L208
https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L265

## Tool used

Manual Review

## Recommendation
The correct approach would be to check if the result is negative before casting to uint256:
```js
int256 balance = int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts))));
return balance > 0 ? uint256(balance) : 0;
```

**Comment by nevillehuang** [comment]
See comment [here](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/649#issuecomment-2283085297)
