### ISSUE TITLE
FlyingBird - A malicious actor can lock any tokenId forever by repeatedly calling Votingescrow : max_lock() just before its lock ends.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#628]
FlyingBird

High

# A malicious actor can lock any tokenId forever by repeatedly calling Votingescrow : max_lock() just before its lock ends.

## Summary & Vulnerability Detail

VotingEscrow::max_lock() is a puplic function with no access control and as long as max_lock_enabled is true, which is the default and can only be changed via team, it is easy to keep any veNFT locked forever by just calling max_lock just before lock time ends repeatedly making token owner unable to withdraw.

```solidity
function max_lock(uint _tokenId) public {
        if(maxLockIdToIndex[_tokenId] !=0 && max_lock_enabled) {
            LockedBalance memory _locked = locked[_tokenId];
            uint unlock_time = (block.timestamp + MAXTIME) / WEEK * WEEK; // Locktime is rounded down to weeks

            if(unlock_time > _locked.end) {
                require(_locked.end > block.timestamp, 'Lock expired');
                require(_locked.amount > 0, 'Nothing is locked');
                require(unlock_time <= block.timestamp + MAXTIME, 'Voting lock can be 52 weeks max');

                _deposit_for(_tokenId, 0, unlock_time, _locked, DepositType.INCREASE_UNLOCK_TIME);
            }
        }
    }

```

## Impact
Manipulating veNFTs and forbidding veNFT's owner  from the ability to withdraw or take whatever decision he wants concerning his/her token.

## Code Snippet
###max_lock
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/VotingEscrow.sol#L911C2-L925C6
## Tool used

Manual Review

## Recommendation
I believe max_lock() should be internal or at least have the correct access control 

Duplicate of #622

**Comment by nevillehuang** [comment]
Invalid, `RewardsDistributorV2` receive rewards when `notifyRewardAmount` is invoked [here](https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L321-L324)
