### ISSUE TITLE
KupiaSec - Casting to `uint` in `RewardDistributorV2::ve_for_at` is not safe

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#635]
KupiaSec

Medium

# Casting to `uint` in `RewardDistributorV2::ve_for_at` is not safe

## Summary

In [RewardDistributorV2::ve_for_at](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L134) function there is a casting of `int256` to `uint`.
However in Solidity casting negative number to `uint` does not revert, instead it underflows to large number. Hence this function will return incorrect value and affects the reward distribution if other protocols use this function.

## Vulnerability Detail

[RewardDistributorV2::ve_for_at](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L134) function is as follows:

```solidity

File: RewardsDistributorV2.sol
134: function ve_for_at(uint _tokenId, uint _timestamp) external view returns (uint) {
135:         address ve = voting_escrow;
136:         uint max_user_epoch = IVotingEscrow(ve).user_point_epoch(_tokenId);
137:         uint epoch = _find_timestamp_user_epoch(ve, _tokenId, _timestamp, max_user_epoch);
138:         IVotingEscrow.Point memory pt = IVotingEscrow(ve).user_point_history(_tokenId, epoch);
139:         return Math.max(uint(int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts))))), 0);  // @audit underflow
140:     }

```

At [L139](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L139) it is supposed to return zero when the calculated balance is a negative number. However it underflows to a large number. It would affect reward distribution if other protocols use this function.

The same issue exists in the following functions:

- `RewardDistributorV2::_checkpoint_total_supply`
- `RewardDistributorV2::_claim`
- `RewardDistributorV2::_claimable`

## Impact

 The function will return incorrect value and it would affect reward distribution if other protocols use this function.

## Code Snippet

https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L139

https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L158

https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L208

https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/RewardsDistributorV2.sol#L265

## Tool used

Manual Review

## Recommendation

It is recommended to fix `RewardDistributorV2::ve_for_at` function to return zero for a negative number as follows:

```diff

File: RewardsDistributorV2.sol
134:    function ve_for_at(uint _tokenId, uint _timestamp) external view returns (uint) {
135:         address ve = voting_escrow;
136:         uint max_user_epoch = IVotingEscrow(ve).user_point_epoch(_tokenId);
137:         uint epoch = _find_timestamp_user_epoch(ve, _tokenId, _timestamp, max_user_epoch);
138:         IVotingEscrow.Point memory pt = IVotingEscrow(ve).user_point_history(_tokenId, epoch);
- 139:       return Math.max(uint(int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts))))), 0);
+ 139:       return uint256(int256(max(pt.bias - pt.slope * int128(int256(_timestamp - pt.ts)), 0)));
140:     }

```

You can find the full fix [here](https://github.com/velodrome-finance/contracts/commit/6485efe9eb5f0884d4a5f20b2489c6087d291092)

**Comment by nevillehuang** [comment]
See comment [here](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/649#issuecomment-2283085297)
