### ISSUE TITLE
Varun_19 - Unsafe casting in RewardsDistributorV2 leads to underflow of veForAt

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#652]
Varun_19

High

# Unsafe casting in RewardsDistributorV2 leads to underflow of veForAt

## Summary
As in solidity if we cast a negative number to uint it doesn't revert instead it underflows to a large number similar situation can arise in veForAt function.
## Vulnerability Detail
Following is veForAt function
```solidity
 function ve_for_at(uint _tokenId, uint _timestamp) external view returns (uint) {
        address ve = voting_escrow;
        uint max_user_epoch = IVotingEscrow(ve).user_point_epoch(_tokenId);
        uint epoch = _find_timestamp_user_epoch(ve, _tokenId, _timestamp, max_user_epoch);
        IVotingEscrow.Point memory pt = IVotingEscrow(ve).user_point_history(_tokenId, epoch);
        return Math.max(uint(int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts))))), 0);
    }
```
As can we can clearly see that balance of a token at specific time is calculated as follows
```solidity
 IVotingEscrow.Point memory pt = IVotingEscrow(ve).user_point_history(_tokenId, epoch);
        return Math.max(uint(int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts))))), 0);
```
The above is supposed to return 0 if the balance gets negative but instead it will return a large postive number.
## Impact
This would lead to incorrect rewards distribution.
## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L139
## Tool used

Manual Review

## Recommendation
Make the following changes 
```solidity
int256 rewards = int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts)));
if (rewards < 0) return 0;
return uint256(rewards);
```

**Comment by nevillehuang** [comment]
See comment [here](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/649#issuecomment-2283085297)
