### ISSUE TITLE
MohammedRizwan - Unsafe casting in `RewardsDistributorV2.sol` would lead to underflow in some functions

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#653]
MohammedRizwan

Medium

# Unsafe casting in `RewardsDistributorV2.sol` would lead to underflow in some functions

## Summary
Unsafe casting in `RewardsDistributorV2` would lead to underflow in some functions

## Vulnerability Detail

When casting to a smaller type, if the value exceeds the range of the target type, the higher order bits are discarded, potentially leading to an overflow. Similarly, if a negative number is cast to an unsigned integer, the result will wrap around to a very large positive number, leading to an underflow.

Check [this](https://zokyo-auditing-tutorials.gitbook.io/zokyo-tutorials/tutorials/tutorial-2-unsafe-casting/understanding-casting) reference for better understanding.

Solidity does not revert when casting a negative number to uint. Instead, it underflows to a large number.

The following functions in `RewardsDistributorV2.sol` have used unsafe casting and affected by this issue.

1) `ve_for_at()`
2) `_checkpoint_total_supply()`
3) `_claim()`
4) `_claimable()`

For example in `ve_for_at()` function, the balance of token at specific time is calculated as shown  below:

```solidity
    function ve_for_at(uint _tokenId, uint _timestamp) external view returns (uint) {
        address ve = voting_escrow;
        uint max_user_epoch = IVotingEscrow(ve).user_point_epoch(_tokenId);
        uint epoch = _find_timestamp_user_epoch(ve, _tokenId, _timestamp, max_user_epoch);
        IVotingEscrow.Point memory pt = IVotingEscrow(ve).user_point_history(_tokenId, epoch);
@>      return Math.max(uint(int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts))))), 0);
    }
```

This supposed to return zero value when the calculated balance is a negative number. However, it underflows to a large number due to the reasons stated above.

## Impact
This would cause incorrect reward distribution due to underflow to large number and all above four functions would return incorrect values as used in different functions.

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L139

Other instances:
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L158

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L208

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/RewardsDistributorV2.sol#L265

## Tool used
Manual Review

## Recommendation
Use openzeppelin's `SafeCast.sol` OR consider returning zero for negative number.

For example:

```diff
-                 uint balance_of = Math.max(uint(int256(old_user_point.bias - dt * old_user_point.slope)), 0);
+               int256 result = int256(old_user_point.bias - dt * old_user_point.slope);
+               if (result < 0 ) return 0;
+               return uint(result);
```

OR

```diff
+    function max(int128 a, int128 b) internal pure returns (int128) {
+        return a > b ? a : b;
+    }


-                 uint balance_of = Math.max(uint(int256(old_user_point.bias - dt * old_user_point.slope)), 0);
+                uint balance_of = uint(int256(max(oldUserPoint.bias - dt * oldUserPoint.slope, 0)));
```

**Comment by nevillehuang** [comment]
See comment [here](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/649#issuecomment-2283085297)
