### ISSUE TITLE
sonny2k - VotingEscrow::increase_unlock_time - It's possible for voters to update their vote tokens unlock time as many times as they wish beyond the 365 day MAX limit, violating protocol invariant.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#666]
sonny2k

Medium

# VotingEscrow::increase_unlock_time - It's possible for voters to update their vote tokens unlock time as many times as they wish beyond the 365 day MAX limit, violating protocol invariant.

## Summary
`VotingEscrow::increase_unlock_time()` - It's possible for voters to update their vote tokens unlock time as many times as they wish beyond the 365 day MAX limit, violating protocol invariant.
 
 - it's made clear throughout the codebase and protocol docs that the maximum lock period for the NFT tokens is 1 year, i.e. 365 days, however, the bug in the `increase_unlock_time()` function makes it possible to repeatedly call this function(in different `block.timestamp` timestamps) to extend the unlock period almost indefinitely(e.g. extend by `MAXTIME` each time), but at least for almost 2 years it seems.
 
## Vulnerability Detail
The buggy function:
 ```solidity
    /// @notice Extend the unlock time for `_tokenId`
    /// @param _lock_duration New number of seconds until tokens unlock
    function increase_unlock_time(uint _tokenId, uint _lock_duration) external nonreentrant {
        assert(_isApprovedOrOwner(msg.sender, _tokenId));

        LockedBalance memory _locked = locked[_tokenId];
        uint unlock_time = (block.timestamp + _lock_duration) / WEEK * WEEK; // Locktime is rounded down to weeks

        require(_locked.end > block.timestamp, 'Lock expired');
        require(_locked.amount > 0, 'Nothing is locked');
        require(unlock_time > _locked.end, 'Can only increase lock duration');
        require(unlock_time <= block.timestamp + MAXTIME, 'Voting lock can be 52 weeks max');

        _deposit_for(_tokenId, 0, unlock_time, _locked, DepositType.INCREASE_UNLOCK_TIME);
    }
 ```

## Impact
 - a potential vote outcome manipulation impact

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/VotingEscrow.sol#L939

## Tool used

Manual Review

## Recommendation
 - should take into account the previous update unlock time's `block.timestamp` and therefore the previous update's timestamp for after `MAXTIME` was added, so that we can know how much time was left to use for future unlock time updates, and save that as a state/storage variable which we will use in the `increase_unlock_time()` to ensure our new unlock time extension doesn't exceed the max limit of 365 days.

## References
This report is inspired by the report from [Immunefi Alchemix Boost #31382](https://github.com/immunefi-team/Bounty_Boosts/blob/main/Alchemix/Report%2031382.md)

**Comment by nevillehuang** [comment]
Duplicate of #665
