### ISSUE TITLE
Xtreem - Potential Integer Underflow in _reset Function Leading to DoS

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#67]
Xtreem

Medium

# Potential Integer Underflow in _reset Function Leading to DoS

## Summary
The `_reset` function can lead to an integer underflow vulnerability. This can occur when the `weughts[_pool]` or `votes[_tokenId][_pool]` values are manipulated, causing critical state variables to be set incorrectly and potentially leading to a DoS.

## Vulnerability Detail
In the `_reset` function, the subtraction of `_votes` from `weights[_pool]` and `votes[_tokenId][_pool]` can cause an underflow if the current values of `weights[_pool` or `votes[_tokenId][_poll]` are less than `_votes. This can lead to unintended behavior and potential DoS conditions, making the contract functions related to the gauge unusable.

## Impact
If the weights of a given gauge are manually changed or manipulated such that the subtraction causes an underflow, all functions related to that gauge might become permanently DoSed. This would prevent users from interacting with the gauge and could disrupt the intended functionality.

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/Voter.sol#L216-L228

## Tool used

Manual Review

## Recommendation
To mitigate this vulnerability, add checks to ensure that `weights[_pool]` and `votes[_tokenId][_pool]` are greater than or equal to `_votes` before performing subtraction. This will prevent any underflow and ensure the contract state variables remain consistent:
```solidity
if (_votes != 0) {
    _updateFor(gauges[_pool]);
    if (weights[_pool] >= _votes) {
        weights[_pool] -= _votes;
    } else {
        weights[_pool] = 0;
    }
    if (votes[_tokenId][_pool] >= _votes) {
        votes[_tokenId][_pool] -= _votes;
    } else {
        votes[_tokenId][_pool] = 0;
    }
    if (_votes > 0) {
        IBribe(external_bribes[gauges[_pool]])._withdraw(uint256(_votes), _tokenId);
        _totalWeight += _votes;
    } else {
        _totalWeight -= _votes;
    }
    emit Abstained(_tokenId, _votes);
}
```
Implementing these checks ensures that the function does not inadvertently set negative values, which could lead to further vulnerabilities or DoS conditions.

**Comment by nevillehuang** [comment]
Invalid, not possible
