### ISSUE TITLE
Minato7namikazi - missed check for the `MAX_REWARD_TOKENS` limit

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#688]
Minato7namikazi

High

# missed check for the `MAX_REWARD_TOKENS` limit

## Vulnerability Detail

 in the `notifyRewardAmount` function:

```solidity
function notifyRewardAmount(address token, uint amount) external lock {
    require(amount > 0);
    if (!isReward[token]) {
      require(IVoter(voter).isWhitelisted(token), "bribe tokens must be whitelisted");
      require(rewards.length < MAX_REWARD_TOKENS, "too many rewards tokens");
    }
    // ... rest of the function
}
```

The bug is that there's a missed check for the `MAX_REWARD_TOKENS` limit when the token is already an existing reward. This could potentially allow the number of reward tokens to exceed the `MAX_REWARD_TOKENS` limit if an attacker repeatedly calls `notifyRewardAmount` with different tokens that are already in the rewards list.

To fix this, we should move the `MAX_REWARD_TOKENS` check outside of the `if (!isReward[token])` condition:

```solidity
function notifyRewardAmount(address token, uint amount) external lock {
    require(amount > 0);
    require(rewards.length < MAX_REWARD_TOKENS, "too many rewards tokens");
    if (!isReward[token]) {
      require(IVoter(voter).isWhitelisted(token), "bribe tokens must be whitelisted");
    }
    // ... rest of the function
}
```

This ensures that the `MAX_REWARD_TOKENS` limit is always enforced, regardless of whether the token is a new or existing reward token. This change prevents potential issues with exceeding the intended maximum number of reward tokens, which could lead to unexpected behavior or gas limit problems in other parts of the contract that iterate over the rewards list.

## Code Snippet

https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/ExternalBribe.sol#L279

## Tool used

Manual Review

**Comment by nevillehuang** [comment]
Invalid, new reward tokens are only pushed when the `isReward` token flag is not allowed yet and only if the token is whitelisted. The check is correctly positioned.
