### ISSUE TITLE
kevinkien - Arbitrary `from` passed to `transferFrom`

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#7]
kevinkien

High

# Arbitrary `from` passed to `transferFrom`

## Summary
The `_deposit_for` function in `VotingEscrow.sol` is potentially vulnerable due to passing an arbitrary from address to the transferFrom function of an ERC20 token (lpToken). This could lead to token loss if the from address has approved this contract to spend their tokens.

## Vulnerability Detail
The `_deposit_for` function allows users to deposit and lock tokens into the contract. However, the following code snippet causes the issue:

```solidity
address from = msg.sender;
if (_value != 0 && deposit_type != DepositType.MERGE_TYPE && deposit_type != DepositType.SPLIT_TYPE) {
  assert(IERC20(lpToken).transferFrom(from, address(this), _value));
}
```
In this code, from is always assigned to `msg.sender` (i.e., the function caller). This means that the contract will always try to transfer tokens from the caller's address to itself. However, if another address (victim) has approved this contract to transfer their tokens, an attacker can call the `_deposit_for` function and specify the victim's address as from. This will result in the victim's tokens being transferred to the contract without their knowledge.

## Impact
If an attacker can manipulate the from parameter, they can steal tokens from any address that has approved this contract. The severity of the vulnerability depends on the level of control the attacker has over the from parameter and the number of tokens approved.

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/VotingEscrow.sol#L803-L806

```solidity
address from = msg.sender;
if (_value != 0 && deposit_type != DepositType.MERGE_TYPE && deposit_type != DepositType.SPLIT_TYPE) {
  assert(IERC20(lpToken).transferFrom(from, address(this), _value));
}
```

## Tool used

Manual Review

## Recommendation
remove the from parameter and always use msg.sender as the sending address

```solidity
if (_value != 0 && deposit_type != DepositType.MERGE_TYPE && deposit_type != DepositType.SPLIT_TYPE) {
+   assert(IERC20(lpToken).transferFrom(msg.sender, address(this), _value));
}
```

**Comment by nevillehuang** [comment]
Invalid, from address is not arbitrary, it is specified by the user calling.
