### ISSUE TITLE
kevinkien - Use safeTransfer/safeTransferFrom consistently instead of transfer/transferFrom

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-velocimeter-judging#8]
kevinkien

Medium

# Use safeTransfer/safeTransferFrom consistently instead of transfer/transferFrom

## Summary
The `_deposit_for` function in `VotingEscrow.sol` inconsistently uses transferFrom for token transfers. While it is used within an assert statement, the lack of explicit error handling for failed transfers could lead to silent failures and incorrect accounting of tokens.

## Vulnerability Detail
The _deposit_for function facilitates depositing and locking tokens for a user. However, in the following code snippet, it uses transferFrom without explicitly checking the return value:

```solidity
if (_value != 0 && deposit_type != DepositType.MERGE_TYPE && deposit_type != DepositType.SPLIT_TYPE) {
  assert(IERC20(lpToken).transferFrom(from, address(this), _value));
}
```
The assert statement will revert the transaction if the transfer fails. However, it doesn't provide any specific error message or logging, making it difficult to diagnose the cause of failure. This lack of error handling can result in silent failures, leading to discrepancies in token balances within the contract.

## Impact
 If a token transfer fails for any reason (e.g., insufficient balance or a non-compliant ERC20 token), the transaction will revert without a clear indication of the problem

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/VotingEscrow.sol#L805

```solidity
if (_value != 0 && deposit_type != DepositType.MERGE_TYPE && deposit_type != DepositType.SPLIT_TYPE) {
        assert(IERC20(lpToken).transferFrom(from, address(this), _value));
}
```

## Tool used

Manual Review

## Recommendation
To ensure consistent and reliable token transfers, replace the transferFrom call with safeTransferFrom. This function, available in OpenZeppelin's IERC20 interface, automatically checks the return value of the transfer and reverts with an error message if it fails.

```solidity
if (_value != 0 && deposit_type != DepositType.MERGE_TYPE && deposit_type != DepositType.SPLIT_TYPE) {
  require(IERC20(lpToken).safeTransferFrom(from, address(this), _value));
}
```

**Comment by nevillehuang** [comment]
Invalid, assert is exactly used to check the return value
