### ISSUE TITLE
Bauchibred - `Pair#currentCumulativePrices()` does not use a fair lp pricing formular

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#90]
Bauchibred

High

# `Pair#currentCumulativePrices()` does not use a fair lp pricing formular

## Summary

Crux of the issue is that the reserves are directly used instead of the determination of prices to be done with a fair LP pricing formular.

## Vulnerability Detail

See both snippets and how the reserves are directly used to determine the prices: https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/Pair.sol#L182-L195

```solidity
    function currentCumulativePrices() public view returns (uint reserve0Cumulative, uint reserve1Cumulative, uint blockTimestamp) {
        blockTimestamp = block.timestamp;
        reserve0Cumulative = reserve0CumulativeLast;
        reserve1Cumulative = reserve1CumulativeLast;

        // if time has elapsed since the last update on the pair, mock the accumulated price values
        (uint _reserve0, uint _reserve1, uint _blockTimestampLast) = getReserves();
        if (_blockTimestampLast != blockTimestamp) {
            // subtraction overflow is desired
            uint timeElapsed = blockTimestamp - _blockTimestampLast;
            reserve0Cumulative += _reserve0 * timeElapsed;
            reserve1Cumulative += _reserve1 * timeElapsed;
        }
    }

  <!-- Also  https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/Pair.sol#L155-L159 -->


    function getReserves() public view returns (uint _reserve0, uint _reserve1, uint _blockTimestampLast) {
        _reserve0 = reserve0;
        _reserve1 = reserve1;
        _blockTimestampLast = blockTimestampLast;
    }
```

And these values are directly used [when getting the twap price too](https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/Pair.sol#L200)

Issue however is the fact that this implementation is easily manipulatable considering the reserves are directly used and protocol does not implement a fair lp pricing formular.

This is quite a popular bug case and a little bit more explanation can be seen in this blog: https://blog.alphaventuredao.io/fair-lp-token-pricing/.

An attack idea using a flash-loan sandwich could be along the lines of:

1. Flash loan and pump the underlying asset to the pool (temporarily faking reserve balances)
2. Attack the target protocol (getting false reserve balances)
3. Dump the asset back and return the borrowed asset.

So to compute Fair LP Price, we would need ways to find Fair Asset Price and Fair Asset Reserve.

## Impact

An attacker could manipulate the cummulative price relatively very easy, considering the reserves are directly used and integrate with the system while the reserves have been manipulated

## Code Snippet

https://github.com/sherlock-audit/2024-06-velocimeter/blob/63818925987a5115a80eff4bd12578146a844cfd/v4-contracts/contracts/Pair.sol#L182-L195

## Tool used

Manual Review

## Recommendation

Do not directly use the reserves while trying to determine the price of tokens, advisable use a similar formular as explained in this [blog](https://blog.alphaventuredao.io/fair-lp-token-pricing/))

**Comment by nevillehuang** [comment]
Invalid, low severity, similar to #487 and #680, `currentCumulativePrices` never called anywhere in the codebase
