### ISSUE TITLE
JuggerNaut63 - Disallow Minting/Transfers to Own Contract Address

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-velocimeter-judging#91]
JuggerNaut63

High

# Disallow Minting/Transfers to Own Contract Address

## Summary
The minting procedure or transfer of tokens to the token contract address itself may result in permanent loss of user tokens. This often happens due to copy and paste errors. The current implementation does not check whether the destination address is the address of the contract itself.

## Vulnerability Detail
On lines 483 to 492, the _'_mint'_ function does not check whether the _'_to'_ destination address is the address of the contract itself. This can cause newly minted or transferred tokens to become permanently stuck in the contract, where they cannot be accessed or moved by the user.

## Impact
If tokens are minted or transferred to the contract address itself, they will be lost permanently. This can cause significant harm to users and reduce trust in the contract.

## Code Snippet
https://github.com/sherlock-audit/2024-06-velocimeter/blob/main/v4-contracts/contracts/VotingEscrow.sol#L483-L492

## Tool used

Manual Review

## Recommendation
Add a check to ensure that the _'_to'_ destination address is not the contract address itself. If the address is a contract address, the function should return an error or revert.

**Comment by nevillehuang** [comment]
Invalid, user input error, invalid based on [sherlock rules](https://github.com/sherlock-protocol/sherlock-v2-docs/tree/29a019b8690eb01df3587868c4d7eac1e3459bda/audits/judging/judging#vii-list-of-issue-categories-that-are-not-considered-valid)

> 4. User input validation: User input validation to prevent user mistakes is not considered a valid issue
