### ISSUE TITLE
dany.armstrong90 - `RewardsDistributorV2.sol` miscalculates the point value.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-velocimeter-judging#96]
dany.armstrong90

High

# `RewardsDistributorV2.sol` miscalculates the point value.

## Summary
`RewardsDistributorV2.sol` miscalculates the point value.
It causes serious problems to the protocol.

## Vulnerability Detail
`RewardsDistributorV2.sol#ve_for_at` function is the following.
```solidity
    function ve_for_at(uint _tokenId, uint _timestamp) external view returns (uint) {
        address ve = voting_escrow;
        uint max_user_epoch = IVotingEscrow(ve).user_point_epoch(_tokenId);
        uint epoch = _find_timestamp_user_epoch(ve, _tokenId, _timestamp, max_user_epoch);
        IVotingEscrow.Point memory pt = IVotingEscrow(ve).user_point_history(_tokenId, epoch);
139:    return Math.max(uint(int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts))))), 0);
    }
```
As can be seen, the order of `Math.max()` and the `uint` type converter is reversed.
Therefore underflow may occur when `pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts)))` is negative.

## Impact
Underflow may occur calculating point value.
The same errors also exist in `_checkpoint_total_supply`, `_claim` and `_claimable` functions.
The issue causes several serious problems to the protocol.

## Code Snippet
- [v4-contracts/contracts/RewardsDistributorV2.sol#L139](https://github.com/sherlock-audit/2024-06-velocimeter-web3-master/tree/main/v4-contracts/contracts/RewardsDistributorV2.sol#L139)
- [v4-contracts/contracts/RewardsDistributorV2.sol#L158](https://github.com/sherlock-audit/2024-06-velocimeter-web3-master/tree/main/v4-contracts/contracts/RewardsDistributorV2.sol#L158)
- [v4-contracts/contracts/RewardsDistributorV2.sol#L208](https://github.com/sherlock-audit/2024-06-velocimeter-web3-master/tree/main/v4-contracts/contracts/RewardsDistributorV2.sol#L208)
- [v4-contracts/contracts/RewardsDistributorV2.sol#L265](https://github.com/sherlock-audit/2024-06-velocimeter-web3-master/tree/main/v4-contracts/contracts/RewardsDistributorV2.sol#L265)

## Tool used

Manual Review

## Recommendation
Modify the `RewardsDistributorV2.sol#ve_for_at` function as follows.
```solidity
    function ve_for_at(uint _tokenId, uint _timestamp) external view returns (uint) {
        address ve = voting_escrow;
        uint max_user_epoch = IVotingEscrow(ve).user_point_epoch(_tokenId);
        uint epoch = _find_timestamp_user_epoch(ve, _tokenId, _timestamp, max_user_epoch);
        IVotingEscrow.Point memory pt = IVotingEscrow(ve).user_point_history(_tokenId, epoch);
--      return Math.max(uint(int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts))))), 0);
++      return uint(SignedMath.max(int256(pt.bias - pt.slope * (int128(int256(_timestamp - pt.ts)))), 0));
    }
```
Modify the other funcions similarly.

**Comment by nevillehuang** [comment]
See comment [here](https://github.com/sherlock-audit/2024-06-velocimeter-judging/issues/649#issuecomment-2283085297)
